// THE FILM PANE — the top band of Concept A's Split Deck.
//
// It shows one of four things and never a fifth: the clip, an indeterminate
// wait, a row that has no film, or a refusal it can explain.
//
// FIVE RULES HOLD THIS PANE, and four of them are about what it must NOT draw.
//
// 1. NEVER THE NEXT CLIP'S POSTER AS A PLACEHOLDER. Every frame carries the
//    broadcast scorebug burned into the pixels — score, inning, count, outs,
//    read off real frames rather than assumed. So pitch N+1's poster shows the
//    result of the at-bat still being scored. The placeholder here is neutral
//    and drawn in CSS; no poster URL reaches this file.
// 2. THE WAIT IS INDETERMINATE. No bar, no ETA, no byte count, no clip
//    duration printed before it plays. Terminal clips run 4.34 to 12.11 MB
//    precisely BECAUSE a longer one holds more play developing, so a
//    determinate bar would tell the scorer that the plate appearance ahead is
//    a long one — timing that is a function of the reveal, which ADR-0046
//    forbids.
// 3. NO GAME-WIDE COUNT. Not here and not anywhere on this surface: a total
//    states how long the game ran, and so whether it went to extras (ADR-0008).
// 4. A row with no film is not an error. Roughly 275 events a game carry no
//    clip and never will, and MLB mints playIds by formula for every
//    intentional walk. Those read as an ordinary row with nothing to watch.
// 5. It is someone else's video, with someone else's bug on it — Marquee,
//    Bally, whoever had the booth. The frame is theirs; the chrome around it
//    is ours, and the two should not be confused.

function Placeholder({ children, tone = 'wait' }) {
  return (
    <div className={`xl-film__placeholder xl-film__placeholder--${tone}`}>
      <span className="xl-film__mark" aria-hidden="true" />
      <p className="xl-film__msg">{children}</p>
    </div>
  )
}

export function FilmPane({ clipUrl, gate, blockedReason, onSkipFilm, onRetry, autoPlay = true }) {
  // Blocked by the world rather than by the film: a full disk, or a host that
  // has stopped answering. Both are worth naming, because both have a remedy
  // the scorer can act on and neither is going to clear itself.
  if (blockedReason) {
    return (
      <div className="xl-film">
        <Placeholder tone="stop">
          {blockedReason === 'quota'
            ? 'This device is out of room for film. Free some space, then pick it back up.'
            : blockedReason === 'host'
              ? 'MLB has stopped serving clips to this device for now. Give it a few minutes.'
              : 'The film stopped arriving.'}
          <button type="button" className="btn xl-film__btn" onClick={onRetry}>
            Try again
          </button>
        </Placeholder>
      </div>
    )
  }

  if (clipUrl) {
    return (
      <div className="xl-film">
        {/* `key` on the URL so the element is replaced rather than re-sourced:
            a <video> handed a new src mid-play keeps the old frame up on some
            builds, which on this surface would be the PREVIOUS play's picture
            sitting under the new play's box. */}
        <video
          key={clipUrl}
          className="xl-film__video"
          src={clipUrl}
          controls
          playsInline
          autoPlay={autoPlay}
          preload="auto"
        />
      </div>
    )
  }

  // NOTHING HAS BEEN SCORED YET, so there is no row to be showing the film of.
  // A null gate means the cursor has not been placed, which is a different
  // thing from a row that has no film — saying "nothing to watch here" before
  // the scorer has started points at a row they have not reached.
  if (!gate) {
    return (
      <div className="xl-film">
        <Placeholder tone="none">The first play is ready when you are.</Placeholder>
      </div>
    )
  }

  // No clip expected for this row, and none ever will be: paperwork, or a
  // playId MLB generated by formula. An ordinary row with nothing to watch.
  if (gate?.reason === 'paperwork' || gate?.reason === 'no-film') {
    return (
      <div className="xl-film">
        <Placeholder tone="none">Nothing to watch here — write it on the card.</Placeholder>
      </div>
    )
  }

  // The film was expected, its URL resolved, and the bytes will not come. This
  // is the ONE consented escape, and it has to read as a decision the scorer
  // makes rather than a fallback that happens to them — or the gate erodes
  // back into the design it replaced within a week of use.
  if (gate?.escapable) {
    return (
      <div className="xl-film">
        <Placeholder tone="stop">
          This clip is not coming.
          <button type="button" className="btn xl-film__btn" onClick={onSkipFilm}>
            Score this one without the film
          </button>
        </Placeholder>
      </div>
    )
  }

  return (
    <div className="xl-film">
      <Placeholder>The film is coming.</Placeholder>
    </div>
  )
}
