// The brand-colour ground truth shared by BOTH identity layers — teams.js's
// MLB treatment system and milbColors.js's MiLB Home/Away system — plus the one
// chain that resolves a MiLB affiliate to a colour pair.
//
// It sits below both on purpose. milbColors.js already reaches teams.js
// transitively (via wpaLogo.js), so putting the chain in either of them and
// importing the other would close an import cycle. Everything here is a leaf:
// two static tables and pure functions over them. See src/lib/CLAUDE.md.
//
// The chain, in one place, read by every MiLB surface:
//
//   1. the affiliate's own researched pair   (data/milb-colors.json)
//   2. its parent MLB org's pair             (via MILB_PARENT_ORG)
//   3. NEUTRAL_FALLBACK_PAIR                 (milbColorPair only)
//
// Step 1 is what changed in July 2026. Before it, the headshot tint jumped
// straight to step 2 and never saw the affiliate at all — a Durham Bulls
// headshot tinted RAYS navy — while the logo tile read step 1 and had no step 2,
// so the two disagreed by construction. There is now one ordering, and both
// teams.js's teamTintColor and milbColors.js's milbTreatmentTile read it.

import { byTeam } from './tuningStore.js'
import MILB_COLORS from './data/milb-colors.json' with { type: 'json' }

// Re-exported raw for the Team Identity Lab, which reads, edits, and POSTs the
// whole store as one file (ADR-0029). Every resolver below reads the derived
// table instead. Schema in src/lib/CLAUDE.md.
export { MILB_COLORS }

// Each MLB club's REAL primary + secondary brand colors — distinct from
// teams.js's TEAM_COLORS, which deliberately picks ONE rival-distinguishing
// accent (sometimes skipping a club's actual navy/blue on purpose). This pair
// is for contexts that want a club's genuine two-tone identity at full
// brightness (e.g. the box score's favor lean-bar diagonal stripe —
// StatBox.jsx), not a subtle single-hue tint. Verified against
// teamcolorcodes.com/mlb-color-codes (2026-07-16), not picked from memory — that
// accent table is hand-picked for a DIFFERENT purpose (distinctiveness), so
// this couldn't reuse its data even if it wanted to.
export const TEAM_COLOR_PAIRS = {
  108: ['#003263', '#BA0021'], // Angels
  109: ['#A71930', '#E3D4AD'], // Diamondbacks
  110: ['#DF4601', '#000000'], // Orioles
  111: ['#BD3039', '#0C2340'], // Red Sox
  112: ['#0E3386', '#CC3433'], // Cubs
  113: ['#C6011F', '#000000'], // Reds
  114: ['#00385D', '#E50022'], // Guardians
  115: ['#333366', '#C4CED4'], // Rockies
  116: ['#0C2340', '#FA4616'], // Tigers
  117: ['#002D62', '#EB6E1F'], // Astros
  118: ['#004687', '#BD9B60'], // Royals
  119: ['#005A9C', '#EF3E42'], // Dodgers
  120: ['#AB0003', '#14225A'], // Nationals
  121: ['#002D72', '#FF5910'], // Mets
  133: ['#003831', '#EFB21E'], // Athletics
  134: ['#27251F', '#FDB827'], // Pirates
  135: ['#2F241D', '#FFC425'], // Padres
  136: ['#0C2C56', '#005C5C'], // Mariners
  137: ['#FD5A1E', '#27251F'], // Giants
  138: ['#C41E3A', '#0C2340'], // Cardinals
  139: ['#092C5C', '#8FBCE6'], // Rays
  140: ['#003278', '#C0111F'], // Rangers
  141: ['#134A8E', '#1D2D5C'], // Blue Jays
  142: ['#002B5C', '#D31145'], // Twins
  143: ['#E81828', '#002D72'], // Phillies
  144: ['#CE1141', '#13274F'], // Braves
  145: ['#27251F', '#C4CED4'], // White Sox
  146: ['#00A3E0', '#EF3340'], // Marlins
  147: ['#003087', '#E4002C'], // Yankees
  158: ['#12284B', '#FFC52F'], // Brewers
}

// Every current MiLB affiliate's teamId -> its parent MLB org's teamId — step 2
// of the chain above, and the reason a farmhand at an affiliate research never
// resolved still gets a real, related identity rather than the neutral
// placeholder. Generated from
// public/data/affiliates.json by scripts/gen-milb-team-colors.mjs — an org's
// farm system changes at most once a year (the offseason PDC realignment), so
// like milbHistory.js this is a hand-run regenerate, not a cron. Re-run that
// script after a realignment; don't hand-edit the block below.
// MILB_PARENT_ORG:BEGIN (generated by scripts/gen-milb-team-colors.mjs)
const MILB_PARENT_ORG = {
  561: 108, // Salt Lake Bees
  559: 108, // Rocket City Trash Pandas
  460: 108, // Tri-City Dust Devils
  526: 108, // Rancho Cucamonga Quakes
  2310: 109, // Reno Aces
  5368: 109, // Amarillo Sod Poodles
  419: 109, // Hillsboro Hops
  516: 109, // Visalia Rawhide
  568: 110, // Norfolk Tides
  418: 110, // Chesapeake Baysox
  493: 110, // Frederick Keys
  548: 110, // Delmarva Shorebirds
  533: 111, // Worcester Red Sox
  546: 111, // Portland Sea Dogs
  428: 111, // Greenville Drive
  414: 111, // Salem RidgeYaks
  451: 112, // Iowa Cubs
  553: 112, // Knoxville Smokies
  550: 112, // South Bend Cubs
  521: 112, // Myrtle Beach Pelicans
  416: 113, // Louisville Bats
  498: 113, // Chattanooga Lookouts
  459: 113, // Dayton Dragons
  450: 113, // Daytona Tortugas
  445: 114, // Columbus Clippers
  402: 114, // Akron RubberDucks
  437: 114, // Lake County Captains
  481: 114, // Hill City Howlers
  342: 115, // Albuquerque Isotopes
  538: 115, // Hartford Yard Goats
  486: 115, // Spokane Indians
  259: 115, // Fresno Grizzlies
  512: 116, // Toledo Mud Hens
  106: 116, // Erie SeaWolves
  582: 116, // West Michigan Whitecaps
  570: 116, // Lakeland Flying Tigers
  5434: 117, // Sugar Land Space Cowboys
  482: 117, // Corpus Christi Hooks
  573: 117, // Asheville Tourists
  3712: 117, // Fayetteville Woodpeckers
  541: 118, // Omaha Storm Chasers
  1350: 118, // Northwest Arkansas Naturals
  565: 118, // Quad Cities River Bandits
  3705: 118, // Columbia Fireflies
  238: 119, // Oklahoma City Comets
  260: 119, // Tulsa Drillers
  456: 119, // Great Lakes Loons
  6482: 119, // Ontario Tower Buzzers
  534: 120, // Rochester Red Wings
  547: 120, // Harrisburg Senators
  426: 120, // Wilmington Blue Rocks
  436: 120, // Fredericksburg Nationals
  552: 121, // Syracuse Mets
  505: 121, // Binghamton Rumble Ponies
  453: 121, // Brooklyn Cyclones
  507: 121, // St. Lucie Mets
  400: 133, // Las Vegas Aviators
  237: 133, // Midland RockHounds
  499: 133, // Lansing Lugnuts
  524: 133, // Stockton Ports
  484: 134, // Indianapolis Indians
  452: 134, // Altoona Curve
  477: 134, // Greensboro Grasshoppers
  3390: 134, // Bradenton Marauders
  4904: 135, // El Paso Chihuahuas
  510: 135, // San Antonio Missions
  584: 135, // Fort Wayne TinCaps
  103: 135, // Lake Elsinore Storm
  529: 136, // Tacoma Rainiers
  574: 136, // Arkansas Travelers
  403: 136, // Everett AquaSox
  401: 136, // Inland Empire 66ers
  105: 137, // Sacramento River Cats
  3410: 137, // Richmond Flying Squirrels
  461: 137, // Eugene Emeralds
  476: 137, // San Jose Giants
  235: 138, // Memphis Redbirds
  440: 138, // Springfield Cardinals
  443: 138, // Peoria Chiefs
  279: 138, // Palm Beach Cardinals
  234: 139, // Durham Bulls
  421: 139, // Montgomery Biscuits
  2498: 139, // Bowling Green Hot Rods
  233: 139, // Charleston RiverDogs
  102: 140, // Round Rock Express
  540: 140, // Frisco RoughRiders
  6324: 140, // Hub City Spartanburgers
  448: 140, // Hickory Crawdads
  422: 141, // Buffalo Bisons
  463: 141, // New Hampshire Fisher Cats
  435: 141, // Vancouver Canadians
  424: 141, // Dunedin Blue Jays
  1960: 142, // St. Paul Saints
  3898: 142, // Wichita Wind Surge
  492: 142, // Cedar Rapids Kernels
  509: 142, // Fort Myers Mighty Mussels
  1410: 143, // Lehigh Valley IronPigs
  522: 143, // Reading Fightin Phils
  427: 143, // Jersey Shore BlueClaws
  566: 143, // Clearwater Threshers
  431: 144, // Gwinnett Stripers
  6325: 144, // Columbus Clingstones
  432: 144, // Rome Emperors
  478: 144, // Augusta GreenJackets
  494: 145, // Charlotte Knights
  247: 145, // Birmingham Barons
  580: 145, // Winston-Salem Dash
  487: 145, // Kannapolis Cannon Ballers
  564: 146, // Jacksonville Jumbo Shrimp
  4124: 146, // Pensacola Blue Wahoos
  554: 146, // Beloit Sky Carp
  479: 146, // Jupiter Hammerheads
  531: 147, // Scranton/Wilkes-Barre RailRiders
  1956: 147, // Somerset Patriots
  537: 147, // Hudson Valley Renegades
  587: 147, // Tampa Tarpons
  556: 158, // Nashville Sounds
  5015: 158, // Biloxi Shuckers
  572: 158, // Wisconsin Timber Rattlers
  249: 158, // Wilson Warbirds
}
// MILB_PARENT_ORG:END

// Step 1 of the chain: `{ [teamId]: [primary, secondary] }` for every affiliate
// research actually resolved. An entry marked `"found": false` carries no
// `pair` and so gets no key here — three do today (482 Corpus Christi, 553
// Knoxville, 1956 Somerset: recent rebrands where only colour NAMES were
// found, never a hex). They fall through to step 2 rather than wearing an
// invented colour, and the lab flags them (milbHasResearchedColor below).
export const MILB_RESEARCHED_PAIRS = byTeam(MILB_COLORS, (e) => e.pair)

// Step 3, the last resort: the same neutral graphite pair wpaBandColors.js's
// chipColorsFor falls back to for an unrecognized team — reused rather than
// inventing a second "unknown team" colour. Only reachable for a team id that
// is in NEITHER table: not a researched affiliate, and with no parent org
// (a complex/rookie-league or otherwise unaffiliated club).
export const NEUTRAL_FALLBACK_PAIR = ['#6B6558', '#938C7C']

// Steps 1-2 only: `teamId`'s real brand pair — its own if research resolved
// one, else its parent MLB org's — or null when neither exists. The null rung
// is what callers whose contract is "no known colour, render something else
// entirely" read (teams.js's teamTintColor, teamStripeGradient, teamChipColors);
// callers that must paint SOMETHING read milbColorPair below instead. One
// ordering, two endings — not two chains.
export function milbBrandPair(teamId) {
  return MILB_RESEARCHED_PAIRS[teamId] ?? TEAM_COLOR_PAIRS[MILB_PARENT_ORG[teamId]] ?? null
}

// The full chain, steps 1-3 — for every surface that has to render a colour no
// matter what (the MiLB logo tile, the WPA band, the lab's own preview).
export function milbColorPair(teamId) {
  return milbBrandPair(teamId) ?? NEUTRAL_FALLBACK_PAIR
}

// Whether `teamId` has a real researched colour OF ITS OWN — deliberately NOT
// "the chain found something", so the lab still flags an affiliate that is only
// borrowing its parent org's pair, and the three `found: false` clubs stay
// visibly unresolved instead of looking indistinguishable from a
// confidently-researched one.
export function milbHasResearchedColor(teamId) {
  return Boolean(MILB_RESEARCHED_PAIRS[teamId])
}
