// Express Lane Tier 3 — the staging runner (src/lib/expresslane/runner.js).
//
// Every test here runs offline and instantly: the resolver, the downloader,
// the byte store and the clock are all injected. Nothing reaches
// sporty-clips.mlb.com, which matters more than usual — that host blocks
// automated access after roughly 25 requests in a few minutes.
import assert from 'node:assert/strict'
import test from 'node:test'
import { createStagingRunner } from '../src/lib/expresslane/runner.js'
import { createJob, gateFor } from '../src/lib/expresslane/staging.js'

const pitch = (n) => ({ key: `p${n}`, playId: `p${n}`, halfIndex: 1 })
const paperwork = (n) => ({ key: `a${n}`, playId: null, halfIndex: 1 })

// A downloader that answers from a table of playId -> outcome, records the
// order it was asked in, and refuses to be called twice at once.
function fakeClips(outcomes = {}) {
  const asked = []
  let inFlight = 0
  let maxInFlight = 0
  const fetchClip = async (url) => {
    asked.push(url)
    inFlight += 1
    maxInFlight = Math.max(maxInFlight, inFlight)
    await Promise.resolve()
    inFlight -= 1
    const outcome = outcomes[url] ?? { ok: true, status: 200, blob: new Blob(['x']) }
    if (outcome.throws) throw new Error('network')
    return outcome
  }
  return {
    fetchClip,
    asked,
    get maxInFlight() {
      return maxInFlight
    },
  }
}

// A byte store that lives in a Map. `putOutcome` lets one test make the disk
// refuse.
function fakeStore({ putOutcome = () => 'stored', staged = [] } = {}) {
  const rows = new Set(staged)
  const deleted = []
  return {
    rows,
    deleted,
    async putClip(gamePk, playId) {
      const outcome = putOutcome(playId)
      if (outcome === 'stored') rows.add(playId)
      return outcome
    },
    async deleteClips(gamePk, playIds) {
      for (const playId of playIds) {
        rows.delete(playId)
        deleted.push(playId)
      }
      return playIds.length
    },
    async stagedPlayIds() {
      return new Set(rows)
    },
  }
}

// Build a runner over one half of rows. The clock is a no-op, so a test never
// waits for the politeness gap or the retry backoff.
function harness({
  rows,
  resolve,
  outcomes,
  store = fakeStore(),
  lookbehind,
  horizon,
  sleep = async () => {},
} = {}) {
  const clips = fakeClips(outcomes)
  const resolveClip = resolve ?? (async (playId) => `https://clip/${playId}`)
  const runner = createStagingRunner({
    job: createJob({ gamePk: 823035 }),
    resolveClip,
    fetchClip: clips.fetchClip,
    store,
    sleep,
    lookbehind,
    horizon,
  })
  return { runner, clips, store, rows }
}

// Let the loop run to wherever it parks.
const settle = async () => {
  for (let i = 0; i < 8; i += 1) await new Promise((r) => setTimeout(r, 0))
}

// --- the ordinary pass ----------------------------------------------------

test('the runner stages a half in queue order, one clip at a time', async () => {
  const h = harness()
  await h.runner.addHalf([pitch(1), paperwork(1), pitch(2), pitch(3)])
  await h.runner.start()
  assert.deepEqual(h.clips.asked, ['https://clip/p1', 'https://clip/p2', 'https://clip/p3'])
  assert.equal(h.clips.maxInFlight, 1, 'concurrency buys nothing at 2.1 Mbps — never add a pool')
  assert.equal(h.runner.getJob().state, 'complete')
})

test('paperwork costs no request at all', async () => {
  const h = harness()
  await h.runner.addHalf([paperwork(1), paperwork(2)])
  await h.runner.start()
  assert.deepEqual(h.clips.asked, [])
})

test('the queue only ever holds the halves it was given', async () => {
  // There is no whole-game builder to call, and this is why: a queue holding
  // the whole game states how many innings it ran (ADR-0008).
  const h = harness()
  await h.runner.addHalf([pitch(1)])
  assert.equal(h.runner.getJob().queue.length, 1)
  await h.runner.addHalf([pitch(2)])
  assert.equal(h.runner.getJob().queue.length, 2)
})

// --- resume ---------------------------------------------------------------

test('a half-staged game resumes without fetching what is already on the disk', async () => {
  const store = fakeStore({ staged: ['p1', 'p2'] })
  const h = harness({ store })
  await h.runner.addHalf([pitch(1), pitch(2), pitch(3)])
  await h.runner.start()
  assert.deepEqual(h.clips.asked, ['https://clip/p3'], 'p1 and p2 were already here')
})

// --- the film gate, driven ------------------------------------------------

test('a phantom playId does not deadlock the queue (#1024)', async () => {
  // Every intentional walk carries playIds MLB generated by formula. They
  // resolve to nothing, forever. A queue that waited on one would stop here.
  const h = harness({
    resolve: async (playId) => (playId === 'p2' ? null : `https://clip/${playId}`),
  })
  await h.runner.addHalf([pitch(1), pitch(2), pitch(3)])
  await h.runner.start()
  const job = h.runner.getJob()
  assert.equal(job.state, 'complete', 'the queue drained past the row with no film')
  assert.equal(gateFor(job, pitch(2)).blocked, false)
  assert.equal(gateFor(job, pitch(2)).reason, 'no-film')
  assert.equal(gateFor(job, pitch(2)).escapable, false, 'and it never asked the scorer')
  assert.equal(job.staged.has('p3'), true, 'the rows after it staged normally')
})

test('the cursor cannot be moved past a clip that has not arrived', async () => {
  const h = harness({
    outcomes: { 'https://clip/p2': { ok: false, status: 404, blob: null } },
  })
  await h.runner.addHalf([pitch(1), pitch(2)])
  await h.runner.start()
  await h.runner.moveCursor('p1')
  assert.equal(await h.runner.moveCursor('p2'), 'p1')
})

test('the consented escape moves the cursor past a clip whose bytes will not come', async () => {
  const h = harness({
    outcomes: { 'https://clip/p2': { ok: false, status: 500, blob: null } },
  })
  await h.runner.addHalf([pitch(1), pitch(2)])
  await h.runner.start()
  await h.runner.moveCursor('p1')
  await h.runner.skipFilm('p2')
  assert.equal(await h.runner.moveCursor('p2'), 'p2')
})

// --- refusals -------------------------------------------------------------

test('a 403 stops the job rather than earning a longer ban', async () => {
  const h = harness({
    outcomes: { 'https://clip/p1': { ok: false, status: 403, blob: null } },
  })
  await h.runner.addHalf([pitch(1), pitch(2)])
  await h.runner.start()
  const job = h.runner.getJob()
  assert.equal(job.state, 'blocked')
  assert.equal(job.blockedReason, 'host')
  assert.deepEqual(h.clips.asked, ['https://clip/p1'], 'it did not try the next clip either')
})

test('a full disk blocks with its own reason, not as a failed clip', async () => {
  const store = fakeStore({ putOutcome: () => 'quota' })
  const h = harness({ store })
  await h.runner.addHalf([pitch(1), pitch(2)])
  await h.runner.start()
  const job = h.runner.getJob()
  assert.equal(job.state, 'blocked')
  assert.equal(job.blockedReason, 'quota')
  assert.equal(h.clips.asked.length, 1, 'the next clip would hit the same wall')
})

test('a run of failed downloads blocks the job', async () => {
  const h = harness({ outcomes: { 'https://clip/p1': { throws: true } } })
  await h.runner.addHalf([pitch(1)])
  await h.runner.start()
  const job = h.runner.getJob()
  assert.equal(job.state, 'blocked')
  assert.equal(job.blockedReason, 'failures')
})

test('starting a blocked job does not drive it back into the wall', async () => {
  // A block is the world's doing. Retrying it silently earns a longer ban and
  // hides why the job stopped, so only a deliberate resume clears one.
  const h = harness({
    outcomes: { 'https://clip/p1': { ok: false, status: 403, blob: null } },
  })
  await h.runner.addHalf([pitch(1)])
  await h.runner.start()
  assert.equal(h.runner.getJob().state, 'blocked')
  await h.runner.start()
  assert.equal(h.clips.asked.length, 1, 'starting again asked for nothing')
})

test('resuming after a block picks the same clip back up', async () => {
  const outcomes = { 'https://clip/p1': { throws: true } }
  const h = harness({ outcomes })
  await h.runner.addHalf([pitch(1)])
  await h.runner.start()
  assert.equal(h.runner.getJob().state, 'blocked')
  assert.ok(h.clips.asked.length > 0)
  delete outcomes['https://clip/p1']
  await h.runner.resume()
  assert.equal(h.runner.getJob().staged.has('p1'), true)
})

// --- eviction -------------------------------------------------------------

test('clips behind the scorer are evicted, and a lookbehind is kept', async () => {
  const rows = Array.from({ length: 8 }, (unused, i) => pitch(i + 1))
  const h = harness({ lookbehind: 2 })
  await h.runner.addHalf(rows)
  await h.runner.start()
  await h.runner.moveCursor('p1')
  await h.runner.moveCursor('p6')
  assert.deepEqual(h.store.deleted, ['p1', 'p2', 'p3'], 'p4 and p5 are the lookbehind')
  assert.equal(h.runner.getJob().staged.has('p1'), false, 'the job forgot what really went')
})

// --- the late-publication sweep -------------------------------------------

test('a clip that publishes late is picked up on the sweep, not written off', async () => {
  // Clips lag the pitch by 8 to 26 minutes, so a scorer who opens a game just
  // after the last out meets the publication frontier, not the bandwidth one.
  let published = false
  const h = harness({
    resolve: async (playId) => {
      if (playId !== 'p2') return `https://clip/${playId}`
      return published ? 'https://clip/p2' : null
    },
  })
  await h.runner.addHalf([pitch(1), pitch(2), pitch(3)])
  published = false
  await h.runner.start()
  assert.equal(h.runner.getJob().unfilmed.has('p2'), true, 'the queue moved past it')
  published = true
  await h.runner.resume()
  assert.equal(h.runner.getJob().staged.has('p2'), true, 'and came back for it')
})

test('the sweep leaves a game with nothing to re-ask alone', async () => {
  const h = harness()
  await h.runner.addHalf([pitch(1)])
  await h.runner.start()
  assert.equal(h.runner.getJob().state, 'complete')
  assert.equal(h.clips.asked.length, 1)
})

// --- pausing --------------------------------------------------------------

test('a paused job stops asking, and carries on where it stopped', async () => {
  const h = harness()
  await h.runner.addHalf([pitch(1)])
  await h.runner.start()
  assert.equal(h.clips.asked.length, 1)

  h.runner.pause()
  await h.runner.addHalf([pitch(2), pitch(3)])
  assert.equal(h.clips.asked.length, 1, 'a paused job does not fetch the new half')

  await h.runner.resume()
  assert.deepEqual(h.clips.asked, ['https://clip/p1', 'https://clip/p2', 'https://clip/p3'])
})

test('nothing is fetched before start, so the resume read comes first', async () => {
  const store = fakeStore({ staged: ['p1'] })
  const h = harness({ store })
  await h.runner.addHalf([pitch(1), pitch(2)])
  assert.deepEqual(h.clips.asked, [], 'the queue is filled, and it waits')
  await h.runner.start()
  assert.deepEqual(h.clips.asked, ['https://clip/p2'])
})

// --- the loop can be woken ------------------------------------------------

test('a half arriving while the loop naps does not have to wait the nap out', async () => {
  // The clock here answers the politeness gap and hangs on the long waits, which
  // is what a real 90-second re-sweep looks like from inside the loop.
  //
  // THIS IS THE STALL `?nofilm` FOUND. A half whose film has finished staging
  // drains; the loop settles into the re-sweep nap holding its re-entry guard;
  // the scorer finishes the half and steps into the next one. `addHalf` queued
  // the rows and called `pump`, which returned at once against that guard — so
  // the new half sat unstaged and the surface showed "Getting the first few
  // plays." for up to a minute and a half.
  const h = harness({ sleep: async (ms) => (ms >= 5000 ? new Promise(() => {}) : undefined) })
  await h.runner.addHalf([pitch(1)])
  h.runner.start()
  await settle()
  assert.deepEqual(h.clips.asked, ['https://clip/p1'], 'the first half staged and drained')
  assert.equal(h.runner.getJob().state, 'complete', 'the loop is parked in the re-sweep nap')

  await h.runner.addHalf([pitch(2)])
  await settle()
  assert.deepEqual(
    h.clips.asked,
    ['https://clip/p1', 'https://clip/p2'],
    'the next half is staged without waiting the nap out',
  )
  h.runner.stop()
})

// --- the staging plans, driven end to end ---------------------------------

test('on demand fetches one row, then waits for the scorer', async () => {
  const h = harness({ horizon: 1 })
  await h.runner.addHalf([pitch(1), pitch(2), pitch(3)])
  await h.runner.start()
  assert.deepEqual(h.clips.asked, ['https://clip/p1'], 'only the row about to be needed')

  await h.runner.moveCursor('p1')
  await settle()
  assert.deepEqual(h.clips.asked, ['https://clip/p1', 'https://clip/p2'], 'the tap brings the next')

  await h.runner.moveCursor('p2')
  await settle()
  assert.equal(h.clips.asked.length, 3, 'and so on, one play at a time')
  h.runner.stop()
})

test('on demand still refuses to let the cursor pass the picture', async () => {
  const h = harness({ horizon: 1 })
  await h.runner.addHalf([pitch(1), pitch(2)])
  await h.runner.start()
  // p2 has not been fetched, because nothing has asked for it yet.
  assert.equal(await h.runner.moveCursor('p2'), null, 'the gate holds under every plan')
  assert.equal(gateFor(h.runner.getJob(), pitch(2)).blocked, true)
  h.runner.stop()
})

test('staying ahead runs the whole half without being asked', async () => {
  const h = harness()
  await h.runner.addHalf([pitch(1), pitch(2), pitch(3)])
  await h.runner.start()
  assert.equal(h.clips.asked.length, 3, 'the default plan does not wait to be prompted')
})
