// Slice D of #1128 — the classification behind the sweep.
//
// One entry per `var(--seal*)` read in src/styles/, keyed "file:line". Each
// says where that read goes and why. Three destinations:
//
//   stays   — a reveal is possible on that surface (or finding 9's
//             must-survive list names it). The token keeps its meaning here.
//   marker  — rank / flag / "this one stands out" emphasis. --marker.
//   struct  — a structural token: a rule, a neutral, a club accent, an action
//             colour. Borders on controls that are neither a cover nor a
//             highlight land here, and most of the sweep is this.
//
// `to` is the literal replacement for the whole var(--seal*) EXPRESSION on
// that line (including any color-mix wrapper); `stays` rows carry no `to`.
//
// Three house recipes carry --marker, each with existing precedent in the
// repo, because the token is a FILL colour and cannot be text or a hairline:
//   fill   var(--marker)                                      + --text-heading
//   wash   color-mix(in srgb, var(--marker) 16%, var(--paper-2))
//   rule   color-mix(in srgb, var(--marker) 70%, var(--text-heading))

// [dest, why, from, to]
export const DECISIONS = {
  // ================================================================ STAYS
  '03-slate-header.css:481': ['stays', 'the Scores Unlocked switch, ON — it lifts every seal on the slate (ADR-0026)'],
  '03-slate-header.css:483': ['stays', 'the Scores Unlocked switch, ON'],
  '03-slate-header.css:484': ['stays', 'the Scores Unlocked switch, ON'],
  '05-masthead-nav.css:265': ['stays', 'the @ watermark — must-survive'],
  '06-loader-and-cards.css:620': ['stays', "the slate card's @ watermark — must-survive"],
  '07-team-logo-and-buttons.css:462': ['stays', 'the live-edge chip REPLACES the reveal action in the innings bar'],
  '07-team-logo-and-buttons.css:482': ['stays', 'the live-edge dot, same chip'],
  '07-team-logo-and-buttons.css:495': ['stays', 'THE reveal button'],
  '07-team-logo-and-buttons.css:496': ['stays', 'THE reveal button'],
  '07-team-logo-and-buttons.css:497': ['stays', 'THE reveal button'],
  '07-team-logo-and-buttons.css:583': ['stays', 'the Game Log mint strip — ADR-0035, the one action that leaves something on the far side of a seal'],
  '07-team-logo-and-buttons.css:584': ['stays', 'the Game Log mint strip — ADR-0035'],
  '09-team-info.css:62': ['stays', 'club band, unthemed fallback of the club-accent slot (ADR-0030)'],
  '09-team-info.css:107': ['stays', 'club band, unthemed fallback (ADR-0030)'],
  '09-team-info.css:122': ['stays', 'club band, unthemed fallback (ADR-0030)'],
  '09-team-info.css:133': ['stays', 'club band, unthemed fallback (ADR-0030)'],
  '12-sealbox.css:17': ['stays', 'THE cover face, and the copy each torn half is cut from'],
  '12-sealbox.css:18': ['stays', 'THE cover face and the tear'],
  '12-sealbox.css:58': ['stays', 'the cover copy'],
  '12-sealbox.css:67': ['stays', 'the cover copy'],
  '12-sealbox.css:147': ['stays', 'club band recipe'],
  '12-sealbox.css:795': ['stays', 'club band recipe'],
  '12-sealbox.css:1271': ['stays', 'club band recipe'],
  '12-sealbox.css:1370': ['stays', 'club band recipe'],
  '12-sealbox.css:1408': ['stays', 'club band recipe'],
  '12-sealbox.css:1579': ['stays', 'club band recipe'],
  '13-play-by-play.css:528': ['stays', 'club band recipe'],
  '17-identity-lab-workbench.css:151': ['stays', 'mocks the club band, same fallback'],
  '20-charts.css:175': ['stays', 'club band recipe'],
  '20-charts.css:471': ['stays', 'club band recipe'],
  '20-charts.css:589': ['stays', 'club band recipe'],
  '26b-player-contract.css:301': ['stays', 'the pencilled-in option year — the --seg-dot INDIRECTION, must-survive'],
  '26b-player-contract.css:380': ['stays', 'the pencilled-in option year hatch — must-survive'],
  '29-team-transactions.css:474': ['stays', 'Last 10 home-game kraft ticket the win-loss stamp prints on — must-survive'],
  '29-team-transactions.css:477': ['stays', 'Last 10 home-game kraft ticket — must-survive'],
  '29-team-transactions.css:485': ['stays', 'Last 10 home-game kraft ticket — the pinned #C3996A pairing'],
  '29-team-transactions.css:490': ['stays', 'Last 10 home-game kraft ticket, hover'],
  '29-team-transactions.css:791': ['stays', 'season strip home-game kraft, the same convention'],
  '29-team-transactions.css:812': ['stays', 'season strip home-game kraft, the same convention'],
  '30-standings.css:120': ['stays', 'the standings reveal chip'],
  '30-standings.css:121': ['stays', 'the standings reveal chip'],
  '30-standings.css:122': ['stays', 'the standings reveal chip'],
  '31-wild-card.css:411': ['stays', 'THE due-up pill'],
  '31-wild-card.css:412': ['stays', 'THE due-up pill'],
  '31-wild-card.css:413': ['stays', 'THE due-up pill'],
  '44-pre-game-cards.css:36': ['stays', 'club band recipe — the canonical .metricbar'],
  '46-consent-modal.css:50': ['stays', 'consenting to spoil a day (ADR-0026)'],
  '46-consent-modal.css:51': ['stays', 'consenting to spoil a day (ADR-0026)'],
  '46-consent-modal.css:90': ['stays', 'the Scores Unlocked mode strip'],
  '46-consent-modal.css:91': ['stays', 'the Scores Unlocked mode strip'],
  '62-identity-admin.css:513': ['stays', 'mocks the club band, same fallback'],
  '69-pitch-arsenal.css:26': ['stays', 'club band recipe on the heat band'],
  '69-pitch-arsenal.css:261': ['stays', 'club band recipe on the heat band'],
  '78-offseason.css:353': ['stays', '"Score sealed" on a picked game'],
  '78-offseason.css:359': ['stays', '"Score sealed" on a picked game'],
  'focus/console.css:464': ['stays', 'club band recipe'],
  'scorecard/box.css:195': ['stays', "the at-bat's own seal — the reveal frontier"],
  'scorecard/box.css:196': ['stays', "the at-bat's own seal — the reveal frontier"],
  'scorecard/box.css:207': ['stays', "the at-bat's own seal — the reveal frontier"],
  'scorecard/box.css:247': ['stays', "the at-bat's own seal, flipped"],

  // =============================================================== MARKER
  '05-masthead-nav.css:555': ['marker', '"you are here" on the level ladder', 'var(--seal-cover)', 'color-mix(in srgb, var(--marker) 70%, var(--text-heading))'],
  '05-masthead-nav.css:556': ['marker', '"you are here" on the level ladder', 'color-mix(in srgb, var(--seal-cover) 10%, transparent)', 'color-mix(in srgb, var(--marker) 16%, transparent)'],
  '05-masthead-nav.css:561': ['marker', '"you are here" dot', 'var(--seal-cover)', 'var(--marker)'],
  '05-masthead-nav.css:562': ['marker', '"you are here" dot', 'var(--seal-cover)', 'color-mix(in srgb, var(--marker) 70%, var(--text-heading))'],
  '05-masthead-nav.css:625': ['marker', '"you are here" on the wide level ladder', 'var(--seal-cover)', 'color-mix(in srgb, var(--marker) 70%, var(--text-heading))'],
  '06-loader-and-cards.css:389': ['marker', 'a delayed game is a FLAG, not a cover', 'var(--seal)', 'var(--marker)'],
  '06-loader-and-cards.css:390': ['marker', 'dark heading ink is what holds AA on marker', 'var(--seal-ink)', 'var(--text-heading)'],
  '06-loader-and-cards.css:460': ['marker', 'a postponed card is a flagged card', 'color-mix(in srgb, var(--seal) 15%, var(--surface-card))', 'color-mix(in srgb, var(--marker) 16%, var(--surface-card))'],
  '12-sealbox.css:236': ['marker', 'an ABS challenge still in hand — a live flag', 'var(--seal)', 'var(--marker)'],
  '12-sealbox.css:899': ['marker', 'the pre-pitch staging card reads as prominently as a note line', 'color-mix(in srgb, var(--seal) 14%, var(--surface-card))', 'color-mix(in srgb, var(--marker) 16%, var(--surface-card))'],
  '13-play-by-play.css:466': ['marker', 'a callout is exactly "catches the eye without shouting"', 'var(--seal-deep)', 'color-mix(in srgb, var(--marker) 70%, var(--text-heading))'],
  '21a-box-score-stars.css:52': ['marker', 'the hero star card is the headline entry', 'color-mix(in srgb, var(--seal) 12%, transparent)', 'color-mix(in srgb, var(--marker) 16%, transparent)'],
  '26b-recent-form.css:122': ['marker', 'a form bar trending UP is the flagged state', 'var(--seal)', 'var(--marker)'],
  '27-player-position-innings.css:389': ['marker', 'rehab tape stays TAPE, in the flag colour — the sibling of --il-texture and --win-texture', 'var(--seal-texture)', 'var(--hold-texture)'],
  '27-player-position-innings.css:399': ['marker', 'dark heading ink on hold tape', 'var(--seal-ink)', 'var(--text-heading)'],
  '27-player-position-innings.css:402': ['marker', 'dark heading ink on hold tape', 'var(--seal-ink)', 'var(--text-heading)'],
  '27-player-position-innings.css:478': ['marker', 'a delayed/suspended game is a flag', 'var(--seal)', 'var(--marker)'],
  '27-player-position-innings.css:487': ['marker', 'dark heading ink on marker', 'var(--seal-ink)', 'var(--text-heading)'],
  '28-team-hub.css:184': ['marker', 'the Season Report grade is the headline figure', 'color-mix(in srgb, var(--seal) 12%, transparent)', 'color-mix(in srgb, var(--marker) 16%, transparent)'],
  '28-team-hub.css:194': ['marker', 'the picked grade', 'color-mix(in srgb, var(--seal-hatch) 55%, var(--border-rule))', 'color-mix(in srgb, var(--marker) 70%, var(--text-heading))'],
  '28-team-hub.css:311': ['marker', 'the picked driver row', 'color-mix(in srgb, var(--seal-hatch) 55%, var(--border-rule))', 'color-mix(in srgb, var(--marker) 70%, var(--text-heading))'],
  '28-team-hub.css:312': ['marker', 'the picked driver row', 'color-mix(in srgb, var(--seal) 9%, var(--surface-inset))', 'color-mix(in srgb, var(--marker) 16%, var(--surface-inset))'],
  '28-team-hub.css:422': ['marker', 'THE worked example — a rank is not a reveal; the Close Game pill already asserts text-heading on marker', 'color-mix(in srgb, var(--seal) 16%, transparent)', 'var(--marker)'],
  '28-team-hub.css:662': ['marker', '"you are here" among a strip of ranks', 'color-mix(in srgb, var(--seal) 14%, transparent)', 'color-mix(in srgb, var(--marker) 16%, transparent)'],
  '28-team-hub.css:674': ['marker', 'the arrow onto "you are here"', 'var(--seal-hatch)', 'color-mix(in srgb, var(--marker) 70%, var(--text-heading))'],
  '29-team-transactions.css:758': ['marker', '"you are here" among a season of series blocks', 'var(--seal)', 'color-mix(in srgb, var(--marker) 70%, var(--text-heading))'],
  '31d-prospect-card.css:47': ['marker', '"you are here" on the level ladder', 'var(--seal-cover)', 'color-mix(in srgb, var(--marker) 70%, var(--text-heading))'],
  '31d-prospect-card.css:328': ['marker', 'a chart FLAG is the flag colour', 'var(--seal-cover)', 'var(--marker)'],
  '31c-prospect-filters.css:177': ['marker', 'the amber midpoint of a red-amber-green ramp', 'var(--seal-cover) 60%', 'var(--marker) 60%'],
  '31c-prospect-filters.css:189': ['marker', 'the amber midpoint of a red-amber-green ramp', 'var(--seal-cover) 60%', 'var(--marker) 60%'],
  '38-umpire-pages.css:299': ['marker', '"working today" is a flag', 'var(--seal-ink)', 'var(--text-heading)'],
  '38-umpire-pages.css:300': ['marker', '"working today" is a flag', 'var(--seal)', 'var(--marker)'],
  '48c-stamp-sheet.css:102': ['marker', 'a completed set is a highlight; marker on the album board clears the 3:1 bar with room', 'var(--seal-cover)', 'var(--marker)'],
  '48c-stamp-sheet.css:129': ['marker', 'a completed set is a highlight', 'var(--seal-cover)', 'var(--marker)'],
  '48c-stamp-sheet.css:343': ['marker', 'the completed-set pulse', 'color-mix(in srgb, var(--seal-cover) 55%, transparent)', 'color-mix(in srgb, var(--marker) 55%, transparent)'],
  '48c-stamp-sheet.css:348': ['marker', 'the completed-set pulse', 'color-mix(in srgb, var(--seal-cover) 0%, transparent)', 'color-mix(in srgb, var(--marker) 0%, transparent)'],
  '48c-stamp-sheet.css:354': ['marker', 'the completed-set pulse', 'color-mix(in srgb, var(--seal-cover) 0%, transparent)', 'color-mix(in srgb, var(--marker) 0%, transparent)'],
  '10-lineup.css:571': ['marker', 'a pressed pill is a flag; marker separates from paper far better than kraft did (3.11:1)', 'var(--seal)', 'var(--marker)'],
  '10-lineup.css:572': ['marker', 'a pressed pill is a flag', 'var(--seal)', 'var(--marker)'],
  '55-my-tally-account.css:51': ['marker', 'a sync still pulling is an in-progress flag', 'var(--seal-cover)', 'var(--marker)'],
  '55-my-tally-account.css:52': ['marker', 'a sync still pulling is an in-progress flag', 'var(--seal-cover)', 'color-mix(in srgb, var(--marker) 70%, var(--text-heading))'],
  '56-my-tally-intro.css:120': ['marker', 'a tick literally named markertick', 'var(--seal-cover)', 'var(--marker)'],
  '56-my-tally-intro.css:121': ['marker', 'a tick literally named markertick', 'var(--seal-cover)', 'color-mix(in srgb, var(--marker) 70%, var(--text-heading))'],
  '65-team-records.css:40': ['marker', 'the picked half of a records toggle', 'var(--seal-soft, var(--paper-2))', 'color-mix(in srgb, var(--marker) 16%, var(--paper-2))'],
  '65-team-records.css:41': ['marker', 'the picked half of a records toggle', 'var(--seal)', 'color-mix(in srgb, var(--marker) 70%, var(--text-heading))'],
  '69-hit-chart.css:165': ['marker', 'the ON state of the hard-hit filter — a colourway named for the seal, never on one', 'var(--seal-cover)', 'var(--marker)'],
  '69-hit-chart.css:166': ['marker', 'the ON state of the hard-hit filter', 'var(--seal-hatch)', 'color-mix(in srgb, var(--marker) 70%, var(--text-heading))'],
  '69-hit-chart.css:167': ['marker', 'dark heading ink on marker', 'var(--seal-cover-ink)', 'var(--text-heading)'],
  '70-contracts-grid.css:110': ['marker', 'the cliff bar, already ruled in --marker on the line below it', 'var(--seal)', 'var(--marker)'],
  '71-salaries-league.css:299': ['marker', 'the leading position group', 'var(--seal)', 'color-mix(in srgb, var(--marker) 70%, var(--text-heading))'],
  '74-contract-workbench.css:442': ['marker', 'a diff is a highlighter swipe', 'var(--seal)', 'var(--marker)'],
  '77-express-lane.css:225': ['marker', 'the ON chip on the dark board', 'var(--seal)', 'var(--marker)'],
  '77a-express-lane-entry.css:162': ['marker', 'the picked entry card — one accent for the whole family', 'var(--seal-deep)', 'var(--marker)'],
  '77a-express-lane-entry.css:167': ['marker', 'the picked entry rail', 'var(--seal)', 'var(--marker)'],
  '77a-express-lane-entry.css:196': ['marker', 'the picked entry card', 'var(--seal-deep)', 'var(--marker)'],
  '77a-express-lane-entry.css:221': ['marker', 'the consent rail, same family as the picked card', 'var(--seal)', 'var(--marker)'],
  '78-offseason.css:817': ['marker', 'a season record taped to the page — tape in the flag colour', 'var(--seal-texture)', 'var(--hold-texture)'],
  'designlab/lab.css:237': ['marker', 'a verdict is a flag', 'var(--seal-deep)', 'color-mix(in srgb, var(--marker) 70%, var(--text-heading))'],
  'designlab/lab.css:238': ['marker', 'a verdict is a flag', 'var(--seal-cover)', 'var(--marker)'],
  'designlab/lab.css:239': ['marker', 'dark heading ink on marker', 'var(--seal-cover-ink)', 'var(--text-heading)'],
  'report/challenge-card.css:86': ['marker', 'the picked view of a challenge card', 'var(--seal-soft, var(--paper-2))', 'color-mix(in srgb, var(--marker) 16%, var(--paper-2))'],
  'report/challenge-card.css:87': ['marker', 'the picked view of a challenge card', 'var(--seal)', 'color-mix(in srgb, var(--marker) 70%, var(--text-heading))'],
  'scorecard/box.css:162': ['marker', 'a hand-edited box flagged apart from a derived one', 'var(--seal-cover)', 'var(--marker)'],
  'situational-records/66a-detail.css:150': ['marker', 'the top row of a ranked table', 'color-mix(in srgb, var(--seal-cover) 16%, var(--surface-card))', 'color-mix(in srgb, var(--marker) 16%, var(--surface-card))'],
  '16-identity-lab-shell.css:264': ['marker', 'a strip of tape holding a card down — tape, never a cover', 'var(--seal-texture)', 'var(--hold-texture)'],
  '17-identity-lab-workbench.css:958': ['marker', 'the ON chip’s tape mark', 'var(--seal-texture)', 'var(--hold-texture)'],
  '17-identity-lab-workbench.css:1181': ['marker', 'a torn scrap of tape confirming an action', 'var(--seal-texture)', 'var(--hold-texture)'],

  // =============================================================== STRUCT
  '06-loader-and-cards.css:461': ['struct', 'the dashed edge of a held card is a rule', 'var(--seal-hatch)', 'var(--border-rule)'],
  '06-loader-and-cards.css:476': ['struct', 'a stamp is ink on paper', 'var(--seal-ink)', 'var(--text-heading)'],
  '06-loader-and-cards.css:479': ['struct', 'a stamp is ink on paper', 'var(--seal-ink)', 'var(--text-heading)'],
  '06-loader-and-cards.css:501': ['struct', 'a reason line is body text', 'var(--seal-ink)', 'var(--text-body)'],
  '08a-site-menu.css:51': ['struct', 'a menu glyph spine is chrome', 'var(--seal-cover)', 'var(--accent-primary)'],
  '08a-site-menu.css:132': ['struct', 'the Guide tag is a label chip, not a cover', 'var(--seal-cover)', 'var(--accent-primary)'],
  '08a-site-menu.css:133': ['struct', 'inverse text on an ink chip', 'var(--seal-cover-ink)', 'var(--text-on-ink)'],
  '08a-site-menu.css:350': ['struct', 'a guide-link edge is a rule', 'var(--seal-cover)', 'var(--border-rule)'],
  '08a-site-menu.css:354': ['struct', 'a guide-link spine is chrome', 'var(--seal-cover)', 'var(--accent-primary)'],
  '09-team-info.css:289': ['struct', 'a themed bar falls back to the caption ink, not the cover', 'var(--bar-text, var(--seal-hatch))', 'var(--bar-text, var(--text-caption))'],
  '09-team-info.css:293': ['struct', 'a themed bar falls back to the caption ink', 'var(--bar-text, var(--seal-hatch))', 'var(--bar-text, var(--text-caption))'],
  '09-team-info.css:421': ['struct', 'an info affordance takes the action colour', 'var(--seal)', 'var(--accent-link)'],
  '09-team-info.css:428': ['struct', 'an opened info glyph is an ink chip', 'var(--seal)', 'var(--accent-primary)'],
  '09-team-info.css:429': ['struct', 'an opened info glyph is an ink chip', 'var(--seal)', 'var(--accent-primary)'],
  '09-team-info.css:430': ['struct', 'inverse text on an ink chip', 'var(--seal-ink)', 'var(--text-on-ink)'],
  '09-team-info.css:482': ['struct', 'an info affordance takes the action colour', 'var(--seal)', 'var(--accent-link)'],
  '09-team-info.css:489': ['struct', 'an opened info glyph is an ink chip', 'var(--seal)', 'var(--accent-primary)'],
  '09-team-info.css:490': ['struct', 'an opened info glyph is an ink chip', 'var(--seal)', 'var(--accent-primary)'],
  '09-team-info.css:491': ['struct', 'inverse text on an ink chip', 'var(--seal-ink)', 'var(--text-on-ink)'],
  '10-lineup.css:552': ['struct', 'named in finding 9 — a toggle pill edge is a rule', 'var(--seal)', 'var(--border-rule)'],
  '11-innings.css:37': ['struct', 'the extras banner edge is a rule', 'var(--seal-deep)', 'var(--border-rule)'],
  '11-innings.css:52': ['struct', 'an extras club label is a caption', 'var(--seal-deep)', 'var(--text-caption)'],
  '11-pregame-scoreboard.css:36': ['struct', 'two decorative studs on a board', 'var(--seal-cover)', 'var(--graphite-soft)'],
  '12-sealbox.css:897': ['struct', 'a staging-card edge is a rule', 'var(--seal-hatch)', 'var(--border-rule)'],
  '12-sealbox.css:1007': ['struct', 'a spent mound visit is pencil, not tape', 'var(--seal-hatch)', 'var(--text-caption)'],
  '12-sealbox.css:1107': ['struct', 'the arm now pitching is a heading', 'var(--seal-ink)', 'var(--text-heading)'],
  '13-play-by-play.css:338': ['struct', 'the ladder frame is a rule', 'var(--seal-hatch)', 'var(--border-rule)'],
  '13-play-by-play.css:355': ['struct', 'the shaded strike lane is a pencil shade, not tape', 'var(--seal)', 'color-mix(in srgb, var(--graphite) 22%, var(--paper-3))'],
  '13-play-by-play.css:356': ['struct', 'the lane divider is a rule', 'var(--seal-hatch)', 'var(--border-rule)'],
  '13-play-by-play.css:368': ['struct', 'the ladder head rule', 'var(--seal-hatch)', 'var(--border-rule)'],
  '13-play-by-play.css:373': ['struct', 'a lane head on a pencil shade', 'var(--seal-ink)', 'var(--text-heading)'],
  '13-play-by-play.css:391': ['struct', 'a pitch number on a pencil shade', 'var(--seal-ink)', 'var(--text-heading)'],
  '13-play-by-play.css:478': ['struct', 'marker cannot be text — the callout star is pencil beside a marker rule', 'var(--seal-deep)', 'var(--text-caption)'],
  '14-strike-zone.css:40': ['struct', 'a drawn zone is a pencil rule on paper', 'var(--seal-hatch)', 'var(--graphite)'],
  '14-strike-zone.css:44': ['struct', 'a drawn zone is a pencil rule on paper', 'var(--seal-hatch)', 'var(--graphite)'],
  '14-strike-zone.css:223': ['struct', 'an action button is an ink button', 'var(--seal)', 'var(--accent-primary)'],
  '14-strike-zone.css:224': ['struct', 'an action button edge', 'var(--seal-hatch)', 'var(--accent-primary)'],
  '14-strike-zone.css:225': ['struct', 'inverse text on an ink button', 'var(--seal-ink)', 'var(--text-on-ink)'],
  '14-strike-zone.css:253': ['struct', 'an action button is an ink button', 'var(--seal)', 'var(--accent-primary)'],
  '14-strike-zone.css:254': ['struct', 'an action button edge', 'var(--seal-hatch)', 'var(--accent-primary)'],
  '14-strike-zone.css:255': ['struct', 'inverse text on an ink button', 'var(--seal-ink)', 'var(--text-on-ink)'],
  '20-charts.css:529': ['struct', 'a margin-note mark is pencil', 'var(--seal-deep)', 'var(--text-caption)'],
  '21-box-score.css:666': ['struct', 'an action button is an ink button', 'var(--seal)', 'var(--accent-primary)'],
  '21-box-score.css:667': ['struct', 'an action button edge', 'var(--seal-hatch)', 'var(--accent-primary)'],
  '21-box-score.css:668': ['struct', 'inverse text on an ink button', 'var(--seal-ink)', 'var(--text-on-ink)'],
  '21-box-score.css:713': ['struct', 'the same button floated on a poster', 'var(--seal)', 'var(--accent-primary)'],
  '21-box-score.css:714': ['struct', 'the same button floated on a poster', 'var(--seal-hatch)', 'var(--accent-primary)'],
  '21-box-score.css:715': ['struct', 'inverse text on an ink button', 'var(--seal-ink)', 'var(--text-on-ink)'],
  '21a-box-score-stars.css:89': ['struct', 'star marks are pencil, not tape', 'var(--seal)', 'var(--text-caption)'],
  '26b-player-contract.css:14': ['struct', 'the card frame wash is paper, not tape', 'color-mix(in srgb, var(--seal) 20%, transparent)', 'color-mix(in srgb, var(--rule) 34%, transparent)'],
  '26b-player-contract.css:434': ['struct', 'a contract tag is a ruled chip', 'color-mix(in srgb, var(--seal) 14%, transparent)', 'color-mix(in srgb, var(--rule) 30%, transparent)'],
  '26b-player-contract.css:435': ['struct', 'a contract tag edge is a rule', 'color-mix(in srgb, var(--seal) 45%, transparent)', 'var(--border-rule)'],
  '27-player-position-innings.css:390': ['struct', 'the tape banner edge is a rule', 'var(--seal-hatch)', 'var(--border-rule)'],
  '27-player-position-innings.css:479': ['struct', 'the status banner edge is a rule', 'var(--seal-hatch)', 'var(--border-rule)'],
  '28-team-hub.css:272': ['struct', 'a breakdown label is a caption', 'var(--seal-hatch)', 'var(--text-caption)'],
  '28-team-hub.css:350': ['struct', 'a meter is a quantity, not a highlight', 'var(--seal-hatch)', 'var(--accent-primary)'],
  '28-team-hub.css:421': ['struct', 'the rank chip’s ink — dark heading ink is what holds AA on marker', 'var(--seal-hatch)', 'var(--text-heading)'],
  '28-team-hub.css:777': ['struct', '"how is this scored" is a link', 'var(--seal-hatch)', 'var(--accent-link)'],
  '28-team-hub.css:782': ['struct', 'a link underline', 'color-mix(in srgb, var(--seal-hatch) 40%, transparent)', 'color-mix(in srgb, var(--accent-link) 40%, transparent)'],
  '28-team-hub.css:812': ['struct', 'a detail title is a caption', 'var(--seal-hatch)', 'var(--text-caption)'],
  '29-team-transactions.css:394': ['struct', 'a hover state takes the action colour', 'var(--seal)', 'var(--accent-link)'],
  '29-team-transactions.css:395': ['struct', 'a hover state takes the action colour', 'var(--seal)', 'var(--accent-link)'],
  '29-team-transactions.css:660': ['struct', 'a hover state takes the action colour', 'var(--seal)', 'var(--accent-link)'],
  '29-team-transactions.css:661': ['struct', 'a hover state takes the action colour', 'var(--seal)', 'var(--accent-link)'],
  '29-team-transactions.css:716': ['struct', 'a hover state takes the action colour', 'var(--seal)', 'var(--accent-link)'],
  '29-team-transactions.css:821': ['struct', 'the All-Star Game has its own blue', 'color-mix(in srgb, var(--seal) 14%, var(--bg-page))', 'color-mix(in srgb, var(--allstar-blue) 12%, var(--bg-page))'],
  '29-team-transactions.css:822': ['struct', 'the All-Star Game has its own blue', 'var(--seal)', 'var(--allstar-blue)'],
  '31-wild-card.css:89': ['struct', 'a card head rule', 'var(--seal)', 'var(--border-rule)'],
  '31-wild-card.css:607': ['struct', 'the All-Star Game has its own blue', 'var(--seal)', 'var(--allstar-blue)'],
  '31-wild-card.css:678': ['struct', 'a section head rule', 'var(--seal)', 'var(--border-rule)'],
  '31-wild-card.css:722': ['struct', 'named in finding 9 — the themed rule already does this (09-team-info.css:274)', 'var(--seal)', 'var(--border-rule)'],
  '31-wild-card.css:739': ['struct', 'the divider inside a segmented control', 'var(--seal)', 'var(--border-rule)'],
  '31-wild-card.css:742': ['struct', 'the picked segment is an ink chip', 'var(--seal)', 'var(--accent-primary)'],
  '31-wild-card.css:743': ['struct', 'inverse text on an ink chip', 'var(--seal-ink)', 'var(--text-on-ink)'],
  '31c-prospect-filters.css:247': ['struct', 'the mid tick sits between clay and field — medal amber reads as text where marker cannot', 'var(--seal-cover)', 'var(--award-ink)'],
  '31d-prospect-card.css:323': ['struct', 'a chart mark is ink', 'var(--seal-cover)', 'var(--accent-primary)'],
  '31e-prospect-board.css:77': ['struct', 'a hover state takes the action colour', 'var(--seal-cover)', 'var(--accent-link)'],
  '31e-prospect-board.css:124': ['struct', 'a level chip edge is a rule', 'var(--seal-cover)', 'var(--border-rule)'],
  '31e-prospect-board.css:168': ['struct', 'a line tag edge is a rule', 'var(--seal-cover)', 'var(--border-rule)'],
  '31e-prospect-board.css:208': ['struct', 'a mid band is a caption', 'var(--seal-cover)', 'var(--text-caption)'],
  '34-postseason.css:92': ['struct', 'a bracket column label is a heading', 'var(--seal-ink)', 'var(--text-heading)'],
  '34-postseason.css:218': ['struct', 'a championship is a medal, not a cover', 'var(--seal)', 'var(--award-line)'],
  '34-postseason.css:350': ['struct', 'a round label is a heading', 'var(--seal-ink)', 'var(--text-heading)'],
  '38-umpire-pages.css:131': ['struct', 'inverse text on an ink chip', 'var(--seal-ink)', 'var(--text-on-ink)'],
  '38-umpire-pages.css:132': ['struct', 'a level chip is a label, not a flag', 'var(--seal)', 'var(--accent-primary)'],
  '39-manager-page.css:544': ['struct', 'named in finding 9 — a pill edge is a rule', 'var(--seal)', 'var(--border-rule)'],
  '39-manager-page.css:546': ['struct', 'named in finding 9 — an odds trigger is an ink pill', 'var(--seal)', 'var(--accent-primary)'],
  '39-manager-page.css:547': ['struct', 'inverse text on an ink pill', 'var(--seal-ink)', 'var(--text-on-ink)'],
  '40-game-modals.css:24': ['struct', 'a kicker is a caption', 'var(--seal-hatch)', 'var(--text-caption)'],
  '40-game-modals.css:54': ['struct', 'a drop cap is ink', 'var(--seal-hatch)', 'var(--accent-primary)'],
  '40-game-modals.css:59': ['struct', 'a pull-quote rule is ink', 'var(--seal)', 'var(--accent-primary)'],
  '40-game-modals.css:65': ['struct', 'a sub-kicker is a caption', 'var(--seal-hatch)', 'var(--text-caption)'],
  '40-game-modals.css:207': ['struct', 'a save button is an ink button', 'var(--seal)', 'var(--accent-primary)'],
  '40-game-modals.css:230': ['struct', 'its hover', 'var(--seal-hatch)', 'var(--ink-1)'],
  '44-pre-game-cards.css:156': ['struct', 'a hover state takes the action colour', 'var(--seal)', 'var(--accent-link)'],
  '44-pre-game-cards.css:157': ['struct', 'a hover state takes the action colour', 'var(--seal)', 'var(--accent-link)'],
  '44-pre-game-cards.css:206': ['struct', 'a hover wash', 'color-mix(in srgb, var(--seal) 12%, transparent)', 'color-mix(in srgb, var(--accent-link) 10%, transparent)'],
  '44-pre-game-cards.css:223': ['struct', 'a neutral-park cell is an inset, not a flag', 'color-mix(in srgb, var(--seal) 7%, var(--surface-card))', 'var(--surface-inset)'],
  '44-pre-game-cards.css:226': ['struct', 'its hover', 'color-mix(in srgb, var(--seal) 16%, var(--surface-card))', 'color-mix(in srgb, var(--accent-link) 10%, var(--surface-inset))'],
  '44-pre-game-cards.css:308': ['struct', 'a hover state takes the action colour', 'var(--seal)', 'var(--accent-link)'],
  '44-pre-game-cards.css:336': ['struct', 'a hover state takes the action colour', 'var(--seal)', 'var(--accent-link)'],
  '44-pre-game-cards.css:337': ['struct', 'a hover state takes the action colour', 'var(--seal)', 'var(--accent-link)'],
  '44-pre-game-cards.css:386': ['struct', 'a hover state takes the action colour', 'var(--seal)', 'var(--accent-link)'],
  '45-admin-copy-editor.css:36': ['struct', 'inverse text on an ink button', 'var(--seal-cover-ink)', 'var(--text-on-ink)'],
  '45-admin-copy-editor.css:37': ['struct', 'a save button is an ink button', 'var(--seal-cover)', 'var(--accent-primary)'],
  '45-admin-copy-editor.css:252': ['struct', 'inverse text on an ink button', 'var(--seal-cover-ink)', 'var(--text-on-ink)'],
  '45-admin-copy-editor.css:253': ['struct', 'a confirm button is an ink button', 'var(--seal-cover)', 'var(--accent-primary)'],
  '48-logbook.css:138': ['struct', 'a mode label is a heading', 'var(--seal-cover-ink)', 'var(--text-heading)'],
  '48a-logbook-stats.css:84': ['struct', 'a section head is a heading', 'var(--seal-cover-ink)', 'var(--text-heading)'],
  '48a-logbook-stats.css:406': ['struct', 'a moment figure is a heading', 'var(--seal-cover-ink)', 'var(--text-heading)'],
  '49-passport-book.css:365': ['struct', 'a selection outline is ink', 'var(--seal-cover)', 'var(--accent-primary)'],
  '49-passport-book.css:969': ['struct', 'a placing outline is ink', 'var(--seal-cover)', 'var(--accent-primary)'],
  '49-passport-book.css:980': ['struct', 'a lede is a heading', 'var(--seal-cover-ink)', 'var(--text-heading)'],
  '49-passport-book.css:1017': ['struct', 'an asking outline is ink', 'var(--seal-cover)', 'var(--accent-primary)'],
  '49-passport-book.css:1034': ['struct', 'an order scope is a heading', 'var(--seal-cover-ink)', 'var(--text-heading)'],
  '50-logbook-landing.css:41': ['struct', 'an eyebrow is a heading', 'var(--seal-cover-ink)', 'var(--text-heading)'],
  '50-logbook-landing.css:354': ['struct', 'a step number is ink', 'var(--seal-cover)', 'var(--accent-primary)'],
  '50-logbook-landing.css:423': ['struct', 'a trust panel edge is a rule', 'var(--seal-cover)', 'var(--border-rule)'],
  '50-logbook-landing.css:435': ['struct', 'a drawn wax seal is marketing art, not a spoiler cover', 'var(--seal-cover-ink)', 'var(--accent-primary)'],
  '50-logbook-landing.css:437': ['struct', 'a drawn wax seal is marketing art', 'var(--seal-cover-ink)', 'var(--accent-primary)'],
  '52-highlight-clip-card.css:73': ['struct', 'a hover state takes the action colour', 'var(--seal)', 'var(--accent-link)'],
  '52-highlight-clip-card.css:160': ['struct', 'a play button is an ink button', 'var(--seal)', 'var(--accent-primary)'],
  '52-highlight-clip-card.css:183': ['struct', 'its hover', 'var(--seal-hatch)', 'var(--ink-1)'],
  '52-highlight-clip-card.css:265': ['struct', 'a hover state takes the action colour', 'var(--seal)', 'var(--accent-link)'],
  '52-highlight-clip-card.css:266': ['struct', 'a hover state takes the action colour', 'var(--seal)', 'var(--accent-link)'],
  '52-highlight-clip-card.css:345': ['struct', 'a watch button is an ink button', 'var(--seal)', 'var(--accent-primary)'],
  '52-highlight-clip-card.css:346': ['struct', 'a watch button is an ink button', 'var(--seal)', 'var(--accent-primary)'],
  '52-highlight-clip-card.css:350': ['struct', 'its hover', 'var(--seal-hatch)', 'var(--ink-1)'],
  '52-highlight-clip-card.css:351': ['struct', 'its hover', 'var(--seal-hatch)', 'var(--ink-1)'],
  '53-umpire-tendencies.css:129': ['struct', 'the warm stop between --rule and --marker on one ramp', 'var(--seal) 72%', 'color-mix(in srgb, var(--marker) 55%, var(--rule)) 72%'],
  '53-umpire-tendencies.css:315': ['struct', 'a themed bar rule', 'var(--seal)', 'var(--border-rule)'],
  '54-my-tally.css:95': ['struct', 'a scope label is a heading', 'var(--seal-cover-ink)', 'var(--text-heading)'],
  '54-my-tally.css:133': ['struct', 'a drawn club crest is art, not a spoiler cover', 'var(--seal-cover)', 'var(--accent-primary)'],
  '54-my-tally.css:143': ['struct', 'a drawn club crest is art', 'var(--seal-cover)', 'var(--accent-primary)'],
  '54-my-tally.css:150': ['struct', 'a drawn club crest is art', 'var(--seal-cover)', 'var(--accent-primary)'],
  '55-my-tally-account.css:142': ['struct', 'handoff art is ink', 'var(--seal-cover)', 'var(--accent-primary)'],
  '55-my-tally-account.css:147': ['struct', 'handoff art is ink', 'var(--seal-cover)', 'var(--accent-primary)'],
  '55-my-tally-account.css:153': ['struct', 'handoff art is ink', 'var(--seal-cover)', 'var(--accent-primary)'],
  '55-my-tally-account.css:232': ['struct', 'a receipt edge is a rule', 'var(--seal-cover)', 'var(--border-rule)'],
  '56-my-tally-intro.css:170': ['struct', 'passport art is ink', 'var(--seal-cover)', 'var(--accent-primary)'],
  '61-ballpark-admin.css:176': ['struct', 'an error rail is the negative accent; --seal-edge was never defined', 'var(--seal-edge, var(--kraft-board))', 'var(--accent-negative)'],
  '62-identity-admin.css:303': ['struct', 'a warning rail is the negative accent; --seal-edge was never defined', 'var(--seal-edge, var(--kraft-board))', 'var(--accent-negative)'],
  '65-team-records.css:58': ['struct', 'a group head rule', 'var(--seal)', 'var(--border-rule)'],
  '66-situational-records.css:48': ['struct', 'an eyebrow is a caption', 'var(--seal-cover)', 'var(--text-caption)'],
  '66-situational-records.css:390': ['struct', 'a hover state takes the action colour', 'var(--seal-cover)', 'var(--accent-link)'],
  '67-awards-ledger.css:128': ['struct', 'a tier rule beside --kraft-board ink — medal amber, not tape', 'var(--seal)', 'var(--award-line)'],
  '68-around-the-game.css:610': ['struct', 'a chart category; --marker is already spoken for in this file', 'var(--seal)', 'var(--award-line)'],
  '68-around-the-game.css:648': ['struct', 'the same category in the key', 'var(--seal)', 'var(--award-line)'],
  '69-hit-chart.css:93': ['struct', 'a headline rule runs ink to clay', 'var(--seal-cover)', 'var(--accent-primary)'],
  '70-contracts-grid.css:34': ['struct', 'a tile cap is a rule', 'var(--seal)', 'var(--border-rule)'],
  '70-contracts-grid.css:346': ['struct', 'a table foot rule', 'var(--seal)', 'var(--border-rule)'],
  '71-salaries-league.css:30': ['struct', 'a context line is a caption', 'var(--seal)', 'var(--text-caption)'],
  '71-salaries-league.css:97': ['struct', 'marker cannot be text — a lead rank is heading ink', 'var(--seal)', 'var(--text-heading)'],
  '71-salaries-league.css:177': ['struct', 'the unthemed fallback of a club slot', 'var(--club-2, var(--seal))', 'var(--club-2, var(--accent-primary))'],
  '71-salaries-league.css:367': ['struct', 'a bar cap is ink', 'var(--seal)', 'var(--accent-primary)'],
  '76-workload-marks.css:402': ['struct', 'marker cannot be text — today is heading ink', 'var(--seal)', 'var(--text-heading)'],
  '77-express-lane.css:167': ['struct', 'a turning mark on the dark board is foil', 'var(--seal)', 'var(--album-foil-soft)'],
  '77-express-lane.css:295': ['struct', 'a preroll mark on the dark board is foil', 'var(--seal)', 'var(--album-foil-soft)'],
  '77c-express-lane-deck.css:109': ['struct', 'a base label on the dark board is foil', 'var(--seal)', 'var(--album-foil-soft)'],
  '77c-express-lane-deck.css:199': ['struct', 'a hold label on the dark board is foil', 'var(--seal)', 'var(--album-foil-soft)'],
  'boxlines/boxlines.css:40': ['struct', 'a kicker is a caption', 'var(--seal-hatch)', 'var(--text-caption)'],
  'boxlines/gamelines.css:105': ['struct', 'a heading is a caption', 'var(--seal-hatch)', 'var(--text-caption)'],
  'designlab/lab.css:64': ['struct', "named in finding 9 — the lab's own verdict box edge is a rule", 'var(--seal)', 'var(--border-rule)'],
  'designlab/lab.css:108': ['struct', 'a group title spine is ink', 'var(--seal)', 'var(--accent-primary)'],
  'designlab/lab.css:375': ['struct', 'a warning is the negative accent', 'var(--seal-deep)', 'var(--accent-negative)'],
  'designlab/lab.css:376': ['struct', 'a warning is the negative accent', 'var(--seal)', 'var(--accent-negative)'],
  'situational-records/66a-detail.css:36': ['struct', 'a detail group label is a caption', 'var(--seal-cover)', 'var(--text-caption)'],
  'situational-records/66a-detail.css:188': ['struct', 'a hover state takes the action colour', 'var(--seal-cover)', 'var(--accent-link)'],
}
