// EXPRESS LANE, TIER 1 — the scoring rail for one half-inning.
//
// The rail is the ORDERED, COMPLETE event list a scorer writes on the paper
// card: every pitch, every clipped non-pitch, and every piece of paperwork.
// Clips are a SPARSE OVERLAY on it, not the list itself. Roughly 275 events in
// a nine-inning game carry no `playId` and never will — substitutions, mound
// visits, batter timeouts, plus the stolen bases, wild pitches and caught
// stealings that happen DURING a pitch, where the pitch's own clip shows them.
// Each of those still gets a row. See .scratch/express-lane/PRD.md, "Data
// structure — three tiers".
//
// COSTS NO NEW FETCH. Every field here comes off the `feed/live` payload the
// app already holds, and the parse is COMPOSED from the modules that already
// own it: `pitchInfo.js` classifies a call code, `eventTypes.js` names the
// event families. This file adds an ordering and a shape; it re-derives
// nothing.
//
// THE SPOILER FOOTING — reveal-only, and now atomic with the film.
// `description`, `result` and `pitch` narrate the play, so this module is
// callable only from inside a SealBox's reveal render function, never at
// render top-level and never in an eager useMemo (ADR-0001/0002), the same as
// linescore.js and derive.js.
//
// Express Lane tightens that rule rather than restating it. Under the FILM
// GATE the cursor may not pass the picture, so the prose may not pass it
// either: a scorer who can read "grounds out, second baseman to first" has no
// reason to wait for the clip, and the gate erodes to nothing. So the three
// narrating fields arrive WITH the film or not at all. What a caller may show
// while it waits is what was already true before the advance — the batter, the
// base state, and the count the previous row carried.
//
// ONE HALF-INNING PER CALL, and that is deliberate. There is no whole-game
// builder here, and a caller must not write one by looping over innings until
// the plays run out. A game-wide rail states how many innings the game ran,
// which states whether it went to extras — exactly what ADR-0008 keeps sealed.
// Innings past regulation unlock one at a time as `revealedThrough` advances.

import { halfIndex } from '../select.js'
import { pitchCallCode, pitchDotCategory } from '../playbyplay/pitchInfo.js'
import {
  GAME_ADVISORY_EVENT_TYPE,
  NON_PA_EVENT_TYPES,
  isDelayAdvisory,
} from '../playbyplay/eventTypes.js'

// The three row kinds, which is what the two modes filter on.
//   'pitch'           — a thrown pitch (`isPitch`). Carries a clip in an MLB
//                       game from 2016 on; carries none anywhere else.
//   'nonPitchClipped' — not a pitch, but MLB cut a clip for it: a pickoff
//                       attempt, a pitcher step-off, a pitch-timer violation.
//   'action'          — everything else. No clip exists and none ever will.
export const RAIL_KINDS = ['pitch', 'nonPitchClipped', 'action']

// A WARNING FOR WHOEVER BUILDS THE FILM GATE: a `playId` is not a promise of a
// clip, and `kind: 'nonPitchClipped'` is only as honest as the feed.
//
// Some events carry a playId that MLB GENERATED BY FORMULA rather than minted
// for a clip. Verified live 2026-09-09 on gamePk 823914, atBatIndex 57 — a
// pitchless intentional walk whose four automatic balls carry:
//
//   08239146-0586-1003-000c-f08cd117d70a
//   08239146-0586-1013-000c-f08cd117d70a
//   08239146-0586-1023-000c-f08cd117d70a
//   08239146-0586-1033-000c-f08cd117d70a
//
// The tail repeats, so these cannot be per-clip UUIDs, and a gateway lookup
// found no media for one. A sweep of about 202 games put the rate near 1.2
// such ids per game: every intentional walk, and most pitch-timer violations.
//
// So a gate that reads "this row has a playId, therefore wait for its clip"
// DEADLOCKS on the first intentional walk. The fix belongs in Tier 2 and in
// the gate, not here: the clip index already learns that a playId resolved to
// nothing, and the gate must treat "resolution came back empty" exactly like
// "no playId at all". Do not pattern-match the id string — the constant tail
// is an undocumented magic value that can change without notice. This module
// reports the feed as it stands and does not guess.

// A row's own count, as the feed reports it: the count AS OF this event, so
// for a pitch that is the count AFTER the pitch. The count BEFORE a row is the
// PREVIOUS row's count (0-0 at the head of a plate appearance) — a caller that
// prints a count while the film is still coming must use that one, never this.
//
// `outs` is deliberately dropped. An out is a result, and the film gate hands
// results over with the picture.
function rowCount(event) {
  return {
    balls: event?.count?.balls ?? null,
    strikes: event?.count?.strikes ?? null,
  }
}

// The pitch detail a notation panel draws — the call code, the dot lane it
// takes, the velocity and the pitch type. Classification comes from
// pitchInfo.js's own table, which is the closed list MLB publishes; a second
// spelling of it here could sort a strike into the ball lane.
//
// A pitch always gets one. A NON-pitch gets one only when it carries an
// explicit `details.call.code` — the automatic ball or strike a violation
// awards, which moves the count with no pitch thrown. Skipping those would
// draw a strikeout on two strikes.
//
// The gate is on `details.call`, not on the code alone, and that is load-
// bearing. A pickoff attempt and a pitcher step-off carry a `details.code`
// that is NOT a call code ('1' and 'PSO', verified against gamePk 823035's
// plate appearances 52 and 57), and the table has no entry for either, so both
// would fall to the ball dot and draw a ball for a throw to first.
//
// Reveal-only with the rest of the row: an in-play call code says an out or a
// run happened.
function pitchDetail(event) {
  if (!event?.isPitch && !event?.details?.call?.code) return null
  const code = pitchCallCode(event)
  if (!code) return null
  const pd = event?.pitchData ?? {}
  return {
    callCode: code,
    dot: pitchDotCategory(code),
    mph: typeof pd.startSpeed === 'number' ? pd.startSpeed : null,
    type: event?.details?.type?.description ?? '',
  }
}

// The play's own outcome, carried on its TERMINAL row only. Present for a real
// plate appearance and for the top-level baserunning plays that end a half on
// the bases (an inning-ending caught stealing) — the scorer writes both. Null
// for the feed's `game_advisory` placeholder, which carries the next batter's
// matchup and no result at all.
function playResult(play) {
  const result = play?.result ?? {}
  if (result.eventType === GAME_ADVISORY_EVENT_TYPE) return null
  const isPA = result.type === 'atBat'
  if (!isPA && !NON_PA_EVENT_TYPES.has(result.eventType)) return null
  return {
    event: result.event ?? '',
    eventType: result.eventType ?? '',
    description: result.description ?? '',
    isOut: result.isOut ?? null,
    rbi: typeof result.rbi === 'number' ? result.rbi : null,
  }
}

// The event whose clip carries the play's outcome — Result mode's anchor.
//
// FIRST CHOICE: the last `playEvents[]` element with `isPitch === true` AND a
// `playId`. This held on 570 of 570 plate appearances across 7 games. Every
// one ended on a clip-bearing pitch.
//
// Three fallbacks, kept although not one of them fired:
//   1. The last clip-bearing event of ANY kind, for a plate appearance that
//      ends on a pickoff rather than on a pitch.
//   2. The last pitch, clip or no clip. This is the path MiLB and any game
//      before 2016 takes, where no clip exists anywhere: the row still has to
//      be written, so it is marked terminal and simply carries no video.
//   3. Nothing. A play with no pitch and no clip has no terminal row, which is
//      right — a substitution announcement is not the end of an at-bat.
//
// Returns the index into `events`, or -1.
function terminalEventIndex(events) {
  for (let i = events.length - 1; i >= 0; i -= 1) {
    if (events[i]?.isPitch && events[i]?.playId) return i
  }
  for (let i = events.length - 1; i >= 0; i -= 1) {
    if (events[i]?.playId) return i
  }
  for (let i = events.length - 1; i >= 0; i -= 1) {
    if (events[i]?.isPitch) return i
  }
  return -1
}

// The one thing the rail drops: the feed's own lifecycle bookkeeping. A nested
// `game_advisory` playEvent carries two unrelated things, and eventTypes.js's
// `isDelayAdvisory` already draws the line. "Status Change - Pre-Game",
// "- Warmup" and "- In Progress" lead the first plate appearance of every game
// and say nothing a scorer writes. The in-game stoppages under the same
// eventType — an injury delay, an on-field delay, a coaching visit — are the
// reason a half stopped, so they stay.
//
// Under the film gate this matters twice over. A dropped row is one fewer tap
// on a screen that already waits for pictures, and these three rows would open
// every game with three taps that mean nothing.
function isLifecycleNoise(event) {
  return (
    event?.details?.eventType === GAME_ADVISORY_EVENT_TYPE &&
    !isDelayAdvisory(event?.details?.description)
  )
}

// The rail for one half-inning: every event in feed order, first plate
// appearance first. `half` is 'top' | 'bottom', the same convention the rest of
// InningViewer uses.
//
// Degrades the way every other selector here does. A sparse MiLB feed with no
// `playId` anywhere yields the same rows with `playId: null` throughout, which
// is the honest answer: the notation still gets written, and no clip is
// promised. A missing inning yields an empty array, never a throw.
export function buildRail(feed, inningNum, half) {
  const plays = (feed?.liveData?.plays?.allPlays ?? []).filter(
    (p) => p?.about?.inning === inningNum && p?.about?.halfInning === half,
  )
  const index = halfIndex(inningNum, half)
  const rows = []

  for (const [playPos, play] of plays.entries()) {
    const events = play?.playEvents ?? []
    const result = playResult(play)
    // FALLBACK 4 — a play that has an outcome always lands it on a row.
    //
    // The three searches above can all miss: a play with no pitch and no clip
    // anywhere returns -1, and the outcome the scorer has to write is computed
    // and then dropped. The guard is keyed on the RESULT, not on "the last
    // event of any kind", and that is the point. A paperwork-only play has no
    // result, so it stays non-terminal by construction rather than by luck —
    // a substitution announcement is still not the end of an at-bat, and
    // `isTerminal` still means "this row anchors a play", which is how
    // resultModeRows and the film gate both read it.
    const anchored = terminalEventIndex(events)
    const terminalAt = anchored >= 0 ? anchored : result && events.length ? events.length - 1 : -1
    // `atBatIndex` is the feed's own game-wide plate-appearance number. It is
    // the key's first half, so a feed that omits it (a sparse MiLB payload)
    // falls back to the play's position in this half — still unique here,
    // which is all the key promises.
    const atBatIndex = play?.about?.atBatIndex ?? playPos

    for (const [pos, event] of events.entries()) {
      if (isLifecycleNoise(event)) continue
      const playId = event?.playId ?? null
      const eventIndex = event?.index ?? pos
      const isTerminal = pos === terminalAt
      const kind = event?.isPitch ? 'pitch' : playId ? 'nonPitchClipped' : 'action'
      rows.push({
        // The stable identity. A `playId` is a UUID and is unique across the
        // whole game, so it wins when one exists. The fallback pair is unique
        // within the game for the same reason `atBatIndex` is game-wide.
        key: playId ?? `${atBatIndex}:${eventIndex}`,
        halfIndex: index,
        atBatIndex,
        eventIndex,
        kind,
        playId,
        count: rowCount(event),
        isTerminal,
        // --- the film-gated half. Never read one of these before the clip for
        // this row has arrived; see this file's header.
        description: event?.details?.description ?? '',
        result: isTerminal ? result : null,
        pitch: pitchDetail(event),
      })
    }
  }
  return rows
}

// RESULT MODE — one row per plate appearance, plus the paperwork.
//
// The terminal row is the pitch that carries the outcome, and its clip's own
// title IS the play. The count comes off the data for free, so video is only
// needed for the play itself.
//
// `action` rows ride along, and they must. The film gate blocks the cursor
// until an EXPECTED clip arrives; it never blocks on a row that expects none.
// A mode that dropped the mound visits and the substitutions would leave the
// scorer nothing to write them on.
export function resultModeRows(rows) {
  return (rows ?? []).filter((row) => row.isTerminal || row.kind === 'action')
}

// FULL MODE — every row, in feed order.
//
// This drops nothing, and the pass-through IS the definition rather than a
// stub. Full mode is every pitch, plus the non-pitch events MLB also clips
// (pickoff attempts, step-offs, pitch-timer violations), plus the same
// paperwork Result mode carries. Filtering on "has a clip" would look tighter
// and would be wrong: a pitch with no clip — MiLB, or any game before 2016 —
// still needs its row, and a mode that dropped those would render an empty
// screen instead of a scorable one.
export function fullModeRows(rows) {
  return (rows ?? []).slice()
}
