// Date-level recap artifacts generated by scripts/gen-day-recap.mjs.
//
// A final day's WPA and play-by-play facts do not change, so the browser should
// read one small same-origin file instead of fetching and scanning every game
// after the user reveals the recap. Missing artifacts intentionally fall back
// to the existing on-demand path while the nightly job catches up.

const cache = new Map()

export async function fetchDayRecap(dateStr) {
  if (!dateStr) return null
  if (cache.has(dateStr)) return cache.get(dateStr)

  const promise = fetch(`/data/day-recap/${dateStr}.json`)
    .then((res) => (res.ok ? res.json() : null))
    .catch(() => null)
  cache.set(dateStr, promise)
  return promise
}

export function recapForSport(data, sportId = 1) {
  return data?.bySportId?.[String(sportId)] ?? null
}
