// Daily MLB postseason-odds snapshots, generated by
// scripts/gen-postseason-odds.mjs. Like seasonScoreFor/teamScoreFor, this
// reader selects only the latest snapshot at or before a Team Page's
// spoiler-safe cutoff, so a historical page never renders odds computed with
// knowledge of games past that date.

import { staticJson } from './staticJson.js'

export const fetchPostseasonOdds = staticJson('/data/postseason-odds.json', {
  fallback: { version: 1, generatedAt: null, seasons: {} },
})

export function postseasonOddsFor(data, teamId, season, cutoff) {
  const snapshots = data?.seasons?.[season]?.byTeamId?.[teamId]
  if (!snapshots) return null
  const eligible = Object.keys(snapshots).filter((date) => !cutoff || date <= cutoff).sort()
  return eligible.length ? snapshots[eligible[eligible.length - 1]] : null
}
