// Daily MLB Season Surprise Score snapshots, generated by
// scripts/gen-season-score.mjs. The reader deliberately selects the latest
// snapshot AT OR BEFORE the Team Page's standings cutoff, so a historical page
// never renders a later season result. Missing data is a missing badge.

import { staticJson } from './staticJson.js'

export const fetchSeasonScores = staticJson('/data/season-score.json', {
  fallback: { version: 1, generatedAt: null, seasons: {} },
})

export function seasonScoreFor(data, teamId, season, cutoff) {
  const snapshots = data?.seasons?.[season]?.byTeamId?.[teamId]
  if (!snapshots) return null
  const eligible = Object.keys(snapshots).filter((date) => !cutoff || date <= cutoff).sort()
  return eligible.length ? snapshots[eligible[eligible.length - 1]] : null
}

export function leagueSurpriseScoresFor(data, season, cutoff) {
  const byTeamId = data?.seasons?.[season]?.byTeamId
  if (!byTeamId) return []
  const rows = []
  for (const [teamId, snapshots] of Object.entries(byTeamId)) {
    const eligible = Object.keys(snapshots).filter((date) => !cutoff || date <= cutoff).sort()
    const score = eligible.length ? snapshots[eligible[eligible.length - 1]]?.score : null
    if (score != null) rows.push({ teamId: Number(teamId), score })
  }
  return rows
}
