// Daily MLB Season Surprise Score snapshots, generated by
// scripts/gen-season-score.mjs. The reader deliberately selects the latest
// snapshot AT OR BEFORE the Team Page's standings cutoff, so a historical page
// never renders a later season result. Missing data is a missing badge.
let cached = null

export async function fetchSeasonScores() {
  if (cached) return cached
  try {
    const res = await fetch('/data/season-score.json')
    if (!res.ok) throw new Error(`season-score.json ${res.status}`)
    cached = await res.json()
  } catch {
    cached = { version: 1, generatedAt: null, seasons: {} }
  }
  return cached
}

export function seasonScoreFor(data, teamId, season, cutoff) {
  const snapshots = data?.seasons?.[season]?.byTeamId?.[teamId]
  if (!snapshots) return null
  const eligible = Object.keys(snapshots).filter((date) => !cutoff || date <= cutoff).sort()
  return eligible.length ? snapshots[eligible[eligible.length - 1]] : null
}

export function leagueSurpriseScoresFor(data, season, cutoff) {
  const byTeamId = data?.seasons?.[season]?.byTeamId
  if (!byTeamId) return []
  const rows = []
  for (const [teamId, snapshots] of Object.entries(byTeamId)) {
    const eligible = Object.keys(snapshots).filter((date) => !cutoff || date <= cutoff).sort()
    const score = eligible.length ? snapshots[eligible[eligible.length - 1]]?.score : null
    if (score != null) rows.push({ teamId: Number(teamId), score })
  }
  return rows
}
