// EXPRESS LANE, TIER 3b — the staging queue, and THE FILM GATE.
//
// A pure state machine. Nothing here fetches, stores, waits or renders: it is
// a job object and the transitions over it, so every rule below is testable
// with no network, no IndexedDB and no browser. runner.js drives it; the
// surface reads it.
//
// SPOILER-FREE, and one rule keeps it that way. The job holds playIds, not
// plays: no description, no result, no count, no score. The one thing it could
// leak is SHAPE — a queue that held the whole game would state how many plate
// appearances the game has, which states whether it went to extra innings
// (ADR-0008). So the queue is filled ONE HALF AT A TIME, by `enqueueHalf`, and
// there is no whole-game builder to call.
//
// That constraint turned out to be the right engineering too, which is worth
// saying because it looks like a tax. The sanctioned lookahead is
// `halfIndex <= revealedThrough + 1` (ADR-0003/0010) — one half ahead of the
// scorer. One half of Result-mode film is about 30 MB, which is about two
// minutes at the measured 2.1 Mbps ceiling. So THE SPOILER WINDOW AND THE
// RIGHT STAGING LEAD ARE THE SAME WINDOW: the queue cannot run away from the
// scorer, the working set cannot run away from the disk, and neither needed a
// separate cap to hold it.
//
// THE FILM GATE — the cursor may not pass the picture.
//
// Stated naively ("no clip, no advance") it deadlocks on the first pitching
// change: roughly 275 events in a nine-inning game carry no playId and never
// will. Stated correctly it is one sentence:
//
//   ADVANCE IS BLOCKED ONLY WHILE A CLIP THAT IS EXPECTED HAS NOT ARRIVED.
//   IT IS NEVER BLOCKED WHEN NO CLIP IS EXPECTED.
//
// Three kinds of row, and only the first can ever block:
//
//   a pitch                     gates on its own clip
//   an event INSIDE a pitch     gates on the clip of the pitch it happened on
//     (stolen base, wild pitch,   — which is upstream in rail order, so by the
//      caught stealing, pickoff)    time the cursor reaches this row that clip
//                                   has already been waited for. Nothing left
//                                   to wait on, so it does not block.
//   paperwork                   nothing. Never gates. A mound visit, a
//     (substitution, mound          substitution and a defensive switch get
//      visit, game advisory)        written on the card; there is nothing to
//                                   watch and never will be.
//
// AND THE TRAP THAT IS NOT ANY OF THOSE (issue #1024). Some events carry a
// playId MLB GENERATED BY FORMULA rather than minted for a clip — every
// intentional walk, and most pitch-timer violations, about 1.2 a game. The row
// claims a clip and no clip exists, so a gate reading "has a playId, therefore
// wait" deadlocks about one game in eight. The fix is here and in Tier 2, not
// in rail.js: `markUnfilmed` records that a resolution came back EMPTY, and an
// empty resolution is treated exactly like no playId at all — the row becomes
// paperwork. That covers a 404 and a pulled clip by the same door, and it
// needs no knowledge of the id format. DO NOT pattern-match the id string; the
// constant tail is an undocumented magic value.
//
// A phantom id must also never PROMPT. The consented escape below exists for a
// clip that was expected with evidence — one whose URL resolved and whose
// bytes will not come. If an empty resolution offered the escape instead, it
// would fire about once a game and erode into the fallback the gate was built
// to remove.

// Where a job is. `blocked` is the world's doing — a full disk, or a host that
// has stopped answering. `paused` is the scorer's. Keeping them apart is what
// lets the surface say something true about which one happened.
export const JOB_STATES = ['idle', 'running', 'paused', 'blocked', 'complete']

// What the gate says about one row. Only two of these hold the cursor.
export const GATE_REASONS = [
  'ready', // the bytes are here
  'paperwork', // no clip expected — never waits
  'no-film', // a clip was claimed and resolved to nothing — never waits, never prompts
  'consented', // the scorer chose to score this one without the film
  'evicted', // watched, and its bytes reclaimed behind the cursor — never waits
  'waiting', // expected, not here yet — BLOCKS
  'stalled', // expected, its bytes keep failing — BLOCKS, and offers the escape
]

// How many times a playId is asked for before it is called unfilmed. Clips
// publish 8 to 26 minutes after the pitch, so a just-played at-bat resolves
// empty and then resolves fine; a phantom id resolves empty forever. Nothing
// tells them apart at the time, so the queue asks a few times and then stops
// asking. `markStaged` still overrides an unfilmed mark, so a clip that
// publishes late is picked up if the queue comes back around to it.
const RESOLVE_ATTEMPTS = 3

// How many times one clip's BYTES may fail before the row offers the escape.
const BYTE_FAILURES_BEFORE_ESCAPE = 3

// How many failures in a row, across different clips, mean the world has gone
// away rather than one clip being bad.
const RUN_FAILURES_BEFORE_BLOCKED = 4

// How far behind the cursor a clip is kept before it is evicted.
//
// Not zero, and that is deliberate. Result mode expands a plate appearance
// into its own pitches so the scorer can look again at a play they did not
// read the first time — a 6-4-3 pivot, or a runner going first to third — and
// evicting the instant the cursor passes would take that away at the moment it
// is wanted. Twelve Result-mode clips is about 78 MB, which the working set
// can carry.
const DEFAULT_LOOKBEHIND = 12

function emptyJob(gamePk, mode, feed) {
  return {
    gamePk: Number(gamePk),
    mode, // 'result' | 'full' — it defines the queue, so it is part of the job
    feed, // 'home' | 'away' — the booth, locked for the session
    queue: [], // ordered { key, playId, halfIndex }, one half at a time
    staged: new Set(), // playIds whose bytes are on the disk
    unfilmed: new Set(), // playIds that resolved to nothing — paperwork now
    evicted: new Set(), // playIds watched, then reclaimed behind the cursor
    consented: new Set(), // row keys the scorer chose to score without film
    resolveMisses: new Map(), // playId -> empty resolutions so far
    byteFailures: new Map(), // playId -> failed downloads so far
    runFailures: 0, // failures in a row, whatever the clip
    cursorKey: null,
    state: 'idle',
    blockedReason: null, // 'quota' | 'host' | 'failures' | null
  }
}

// Every transition returns a NEW job. The surface holds one in state and the
// runner hands it back, so a mutated job would be a re-render that never came.
function next(job, patch) {
  return { ...job, ...patch }
}

function copySet(set, add, remove) {
  const out = new Set(set)
  if (add !== undefined) out.add(add)
  if (remove !== undefined) out.delete(remove)
  return out
}

function bump(map, key) {
  const out = new Map(map)
  out.set(key, (out.get(key) ?? 0) + 1)
  return out
}

export function createJob({ gamePk, mode = 'result', feed = 'home' } = {}) {
  return emptyJob(gamePk, mode === 'full' ? 'full' : 'result', feed === 'away' ? 'away' : 'home')
}

// Append one half-inning's rows to the queue, in rail order.
//
// `rows` are rail rows, already put through `resultModeRows` or
// `fullModeRows`. Rows with no playId are queued too: the gate walks the queue
// as well as the rail, and a paperwork row that was missing here would make
// the frontier calculation skip over it rather than pass through it.
//
// Appending the same half twice is a no-op, so a caller may re-enqueue on
// every render without checking.
export function enqueueHalf(job, rows) {
  const known = new Set(job.queue.map((entry) => entry.key))
  const added = []
  for (const row of rows ?? []) {
    if (!row?.key || known.has(row.key)) continue
    known.add(row.key)
    added.push({ key: row.key, playId: row.playId ?? null, halfIndex: row.halfIndex ?? null })
  }
  if (!added.length) return job
  const queue = [...job.queue, ...added]
  // Work arriving un-blocks a drained queue, and only a drained one. A job
  // stopped by a full disk or a silent host stays stopped.
  const state = job.state === 'complete' || job.state === 'idle' ? 'running' : job.state
  return next(job, { queue, state })
}

// A row is COVERED when the cursor may pass it: its bytes are here, no clip
// was ever expected, the clip resolved to nothing, the scorer consented to
// score it without film, or it was watched and its bytes have since been
// reclaimed. Covered is not the same as watchable.
//
// THE EVICTED CASE IS THE ONE THAT LOOKS WRONG AND IS NOT, and leaving it out
// closed a loop that stopped the film for good. Every walk over the queue —
// `nextToStage`, `filmFrontier`, `canAdvanceTo` — starts at the HEAD and asks
// this one question of each row. Eviction takes the bytes off the disk BEHIND
// the cursor, so a job that forgot them without recording why answered "not
// covered" for a play the scorer had already watched: `nextToStage` handed the
// runner the row it had just evicted, `sweep` evicted it again, and the queue
// never reached ahead of the cursor after that. About a half-inning and a half
// into a Result-mode session the loop closed and the surface sat on "The film
// is coming." for the rest of the night.
//
// Covered is the honest answer in any case. The question this predicate asks is
// "may the cursor pass this row", and a row the cursor has already passed is
// settled — the play was watched and it was written down. Whether the bytes are
// still on the disk is a storage fact, not a scoring one.
export function isCovered(job, entry) {
  if (!entry) return false
  if (job.consented.has(entry.key)) return true
  if (!entry.playId) return true
  if (job.unfilmed.has(entry.playId)) return true
  if (job.evicted.has(entry.playId)) return true
  return job.staged.has(entry.playId)
}

// THE GATE, for one row. Takes a rail row or a queue entry — anything with a
// `key` and a `playId`.
//
// `escapable` is true only for a clip whose bytes are proven late: the URL
// resolved, so the film was expected with evidence, and the download has
// failed enough times to say so. An empty resolution never sets it (#1024).
export function gateFor(job, row) {
  if (!row) return { blocked: false, reason: 'paperwork', escapable: false }
  if (job.consented.has(row.key)) return { blocked: false, reason: 'consented', escapable: false }
  if (!row.playId) return { blocked: false, reason: 'paperwork', escapable: false }
  if (job.staged.has(row.playId)) return { blocked: false, reason: 'ready', escapable: false }
  if (job.unfilmed.has(row.playId)) return { blocked: false, reason: 'no-film', escapable: false }
  // Watched, and the bytes reclaimed behind the cursor. It must NOT block: a
  // scorer who steps back past the lookbehind window is looking again at a play
  // already written, and "the film is coming" for a play that is finished is
  // both untrue and — because `gate` is read on the row AHEAD — a second way to
  // deadlock the button.
  if (job.evicted.has(row.playId)) return { blocked: false, reason: 'evicted', escapable: false }
  const failures = job.byteFailures.get(row.playId) ?? 0
  if (failures >= BYTE_FAILURES_BEFORE_ESCAPE) {
    return { blocked: true, reason: 'stalled', escapable: true }
  }
  return { blocked: true, reason: 'waiting', escapable: false }
}

// The furthest row the cursor may reach: the last covered row before the first
// uncovered one. Contiguous by construction — a staged clip beyond a gap does
// not move the frontier, because the scorer cannot get to it.
//
// Null means the head of the queue is not covered yet, which is the state a
// game opens in before the pre-roll lands.
export function filmFrontier(job) {
  let frontier = null
  for (const entry of job.queue) {
    if (!isCovered(job, entry)) break
    frontier = entry.key
  }
  return frontier
}

// Can the cursor move from where it is to `key`? The gate is per row, so this
// only has to check the rows in between — a scorer who taps a chip three plate
// appearances ahead must not jump the frontier.
export function canAdvanceTo(job, key) {
  const from = job.cursorKey ? job.queue.findIndex((entry) => entry.key === job.cursorKey) : -1
  const to = job.queue.findIndex((entry) => entry.key === key)
  if (to < 0) return false
  if (to <= from) return true // backwards is always allowed; it is already scored
  for (let i = from + 1; i <= to; i += 1) {
    if (!isCovered(job, job.queue[i])) return false
  }
  return true
}

// The next playId whose bytes to fetch: the first uncovered row in queue
// order. Strictly in order, and that is not a simplification.
//
// MLB's clip hosts throttle to about 2.1 Mbps and CONCURRENCY DOES NOT HELP —
// seven parallel downloads gave 2.0 Mbps aggregate, the same as one alone,
// while the condensed-game host ran at 134 Mbps on the same connection in the
// same minute. So a pool buys nothing, and out-of-order fetching buys less
// than nothing: it puts staged clips beyond a gap the frontier cannot cross.
export function nextToStage(job) {
  for (const entry of job.queue) {
    if (!isCovered(job, entry)) return entry
  }
  return null
}

// The bytes landed. Clears an earlier unfilmed mark, so a clip that published
// late is picked up rather than written off — and an earlier eviction mark with
// it, so a clip fetched a second time reads as `ready` rather than as one whose
// bytes are still gone.
export function markStaged(job, playId) {
  if (!playId) return job
  return next(job, {
    staged: copySet(job.staged, playId),
    unfilmed: copySet(job.unfilmed, undefined, playId),
    evicted: copySet(job.evicted, undefined, playId),
    byteFailures: new Map(job.byteFailures),
    runFailures: 0,
    state: job.state === 'blocked' ? 'running' : job.state,
    blockedReason: job.state === 'blocked' ? null : job.blockedReason,
  })
}

// The lookup came back empty. Counted, not acted on, until the count runs out
// — then the row becomes paperwork and the queue moves past it.
export function markResolveMiss(job, playId) {
  if (!playId) return job
  const resolveMisses = bump(job.resolveMisses, playId)
  const done = (resolveMisses.get(playId) ?? 0) >= RESOLVE_ATTEMPTS
  return next(job, {
    resolveMisses,
    unfilmed: done ? copySet(job.unfilmed, playId) : job.unfilmed,
  })
}

// This row has no film and never will. Silent: the scorer is not asked, and
// the row reads as an ordinary row with nothing to watch.
export function markUnfilmed(job, playId) {
  if (!playId) return job
  return next(job, { unfilmed: copySet(job.unfilmed, playId) })
}

// Ask once more for the film on rows AHEAD of the cursor that were written
// off. This is the answer to the scorer who opens a game minutes after the
// last out and meets the PUBLICATION frontier rather than the bandwidth
// ceiling: clips lag the pitch by 8 to 26 minutes, so a row the queue passed
// in silence may have film by the time the scorer gets near it.
//
// Rows BEHIND the cursor are left alone. They are already scored, and film
// arriving for a play that has been written is of no use to anybody.
//
// The miss counts are deliberately NOT reset. That is what makes this cheap:
// a row that has already used its attempts costs exactly one more lookup per
// sweep before it goes back to being paperwork.
//
// Returns the same job when there is nothing to re-ask, which is how the
// runner knows to stop sweeping.
export function retryUnfilmedAhead(job) {
  const at = job.queue.findIndex((entry) => entry.key === job.cursorKey)
  const unfilmed = new Set(job.unfilmed)
  let changed = false
  for (let i = at + 1; i < job.queue.length; i += 1) {
    const playId = job.queue[i]?.playId
    if (playId && unfilmed.delete(playId)) changed = true
  }
  return changed ? next(job, { unfilmed, state: 'running' }) : job
}

// A download failed. Two counters, because they answer different questions:
// this clip's count decides whether the row offers the escape, and the run
// count decides whether the whole job is blocked.
export function markByteFailure(job, playId) {
  if (!playId) return job
  const runFailures = job.runFailures + 1
  const blocked = runFailures >= RUN_FAILURES_BEFORE_BLOCKED
  return next(job, {
    byteFailures: bump(job.byteFailures, playId),
    runFailures,
    state: blocked ? 'blocked' : job.state,
    blockedReason: blocked ? 'failures' : job.blockedReason,
  })
}

// The scorer took the escape: score this row without the film. One row, one
// decision, and it is remembered so the offer is not made twice.
export function consentToSkip(job, key) {
  if (!key) return job
  return next(job, { consented: copySet(job.consented, key) })
}

// Move the cursor. Refuses to pass the frontier — the gate is enforced here
// rather than trusted to the caller, because a chip strip, a swipe and a
// keyboard shortcut are three doors onto the same move.
export function setCursor(job, key) {
  if (!canAdvanceTo(job, key)) return job
  return next(job, { cursorKey: key })
}

// The clips behind the scorer that may go. Peak storage is the staging lead
// plus this lookbehind, which is why a 546 MB game never needs 546 MB.
export function evictable(job, { lookbehind = DEFAULT_LOOKBEHIND } = {}) {
  const at = job.queue.findIndex((entry) => entry.key === job.cursorKey)
  if (at < 0) return []
  const out = []
  for (let i = 0; i < at - lookbehind; i += 1) {
    const entry = job.queue[i]
    if (entry?.playId && job.staged.has(entry.playId)) out.push(entry.playId)
  }
  return out
}

// Eviction happened, so the job forgets those bytes. Kept separate from
// `evictable` so a delete that fails does not leave the job lying about what
// is on the disk.
//
// It REMEMBERS the eviction rather than only forgetting the bytes, and that is
// the whole difference between a working queue and one that turns around and
// re-downloads what it just deleted. See `isCovered` for what went wrong when
// it did not.
export function markEvicted(job, playIds) {
  const gone = [...(playIds ?? [])].filter(Boolean)
  if (!gone.length) return job
  const staged = new Set(job.staged)
  const evicted = new Set(job.evicted)
  for (const playId of gone) {
    staged.delete(playId)
    evicted.add(playId)
  }
  return next(job, { staged, evicted })
}

export function pauseJob(job) {
  return job.state === 'blocked' ? job : next(job, { state: 'paused' })
}

// Resume clears a block as well as a pause, because the scorer asking again IS
// the retry — a full disk they have made room on, or a host that has started
// answering. The failure counters go with it, or the next single failure would
// block again at once.
export function resumeJob(job) {
  return next(job, { state: 'running', blockedReason: null, runFailures: 0 })
}

export function blockJob(job, reason) {
  return next(job, { state: 'blocked', blockedReason: reason ?? 'failures' })
}

// The queue is drained. Transient rather than final: enqueueing the next half
// puts the job back to `running`. It says nothing about the game's length,
// which is why it can be shown.
export function markComplete(job) {
  return next(job, { state: 'complete' })
}

// Switch mode mid-session. Result to Full keeps every staged clip and appends
// the rest; Full to Result needs no new bytes at all. The queue clears because
// the mode DEFINES it, and the caller re-enqueues the halves the scorer has
// reached from the newly filtered rows. What survives is everything learned
// about clips rather than about modes: what is staged, what has no film, and
// what the scorer already consented to, and what has already been reclaimed.
export function withMode(job, mode) {
  const wanted = mode === 'full' ? 'full' : 'result'
  if (wanted === job.mode) return job
  return next(job, { mode: wanted, queue: [], state: 'idle' })
}

// Numbers a staging indicator may read, and the two it may not.
//
// NO GAME-WIDE TOTAL AND NO "47 of 333". A total states how long the game ran,
// which states whether it went to extra innings (ADR-0008). And no bar and no
// ETA on the WAIT: terminal clips run 4.34 to 12.11 MB precisely because a
// longer one holds more play developing, so a determinate bar tells the scorer
// that the plate appearance they have not reached is a long one — timing that
// is a function of the reveal, which ADR-0046 forbids. The waiting indicator
// is indeterminate. This returns what is behind the cursor and what state the
// job is in, and nothing that counts forward.
export function stagingStatus(job) {
  const at = job.queue.findIndex((entry) => entry.key === job.cursorKey)
  const frontier = filmFrontier(job)
  const ahead = job.queue.findIndex((entry) => entry.key === frontier)
  return {
    state: job.state,
    blockedReason: job.blockedReason,
    // How many rows of film are ready in front of the scorer. Bounded by the
    // one-half enqueue window, so it never states the game's length.
    filmAhead: at >= 0 && ahead >= at ? ahead - at : 0,
    waiting: job.state !== 'blocked' && nextToStage(job) !== null,
  }
}
